### ISSUE TITLE
Persistance issue in storage.py

### ISSUE THREAD

**Issue by lordgiotto** [home-assistant-libs/python-matter-server#1018]
Hi, I'm facing an issue with version 7.0.0 of the matter-server.
When I add a new node, its configuration is not persisted, therefore the next time I restart my container all the previous devices are not working in Home Assistant.

Looking into the container logs I noticed this exception in `async_save()` in `matter_server/server/storage.py`

```
2024-12-27 00:49:51.602 (MainThread) INFO [matter_server.server.device_controller] Starting Matter commissioning with code using Node ID 1.
2024-12-27 00:49:51.604 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/storage.py", line 169, in async_save
    await self.server.loop.run_in_executor(None, do_save)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/storage.py", line 159, in do_save
    shutil.copy(self.filename, self.filename_backup)
  File "/usr/local/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/8431771981238243350.json'
2024-12-27 00:49:52.445 (Dummy-2) INFO [chip.ChipDeviceCtrl] Established secure session with Device
2024-12-27 00:49:54.835 (Dummy-2) INFO [chip.ChipDeviceCtrl] Commissioning complete
2024-12-27 00:49:54.836 (MainThread) INFO [matter_server.server.device_controller] Commissioned Node ID: 1 vs 1
2024-12-27 00:49:54.837 (MainThread) INFO [matter_server.server.device_controller] Matter commissioning of Node ID 1 successful.
2024-12-27 00:49:54.837 (MainThread) INFO [matter_server.server.device_controller] Interviewing node: 1
2024-12-27 00:49:55.448 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Setting-up node...
2024-12-27 00:49:55.449 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/storage.py", line 169, in async_save
    await self.server.loop.run_in_executor(None, do_save)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/storage.py", line 159, in do_save
    shutil.copy(self.filename, self.filename_backup)
  File "/usr/local/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/8431771981238243350.json'
2024-12-27 00:49:55.450 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Setting up attributes and events subscription.
2024-12-27 00:49:55.823 (MainThread) INFO [matter_server.server.device_controller] <Node:1> Subscription succeeded with report interval [1, 60]
2024-12-27 00:49:55.824 (MainThread) INFO [matter_server.server.device_controller] Commissioning of Node ID 1 completed.
```

It seems that in a recent commit the existence check of `self.filename` before its copy has been removed, and if it doesn't exist the code throws (see screenshot)
<img width="763" alt="image" src="https://github.com/user-attachments/assets/2de48764-87be-459d-a217-f4c122c2946f" />

As a temporary workaround I moved back to version 6.6.1 and persistence works as expected.

Hope it helps :)

**Comment by denfed** [comment]
I have the same issue -- the json file can't be written and the matter devices I have in home assistant get lost when the matter container restarts. Downgrading to 6.6.1 solves this problem for now. Seems like an easy fix :)

**Comment by mortowsic** [comment]
Life saver! finally got my Linkind bulbs to work with the weird error message, hoping that the config will persist now too

**Comment by silverbladeg** [comment]
same issue here, i downgraded to 6.6.1 as well.

**Comment by lboue** [comment]
Salle issue for me too.
