### ISSUE TITLE
Update fails (HACS)

### ISSUE THREAD

**Issue by CFenner** [home-assistant-libs/python-matter-server#113]
<img width="582" alt="Bildschirm­foto 2022-12-01 um 01 41 40" src="https://user-images.githubusercontent.com/9592452/204938466-c4d8c6f9-3c88-4881-abf8-e75504d20453.png">

<img width="813" alt="Bildschirm­foto 2022-12-01 um 01 41 31" src="https://user-images.githubusercontent.com/9592452/204938411-2a24b6e0-bb9a-492b-b9fd-4463af184910.png">

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/integration.py:173 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 01:41:22 (3 occurrences) 
Last logged: 01:42:00

[547650933120] No manifest.json file found 'custom_components/None/manifest.json'
[547584549424] No manifest.json file found 'custom_components/None/manifest.json'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 83, in async_install
    await self.repository.update_repository(force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No manifest.json file found 'custom_components/None/manifest.json'
```

I noticed that the file structure changed, is this still something that one can install as an HACS integration?

**Comment by Jpsy** [comment]
The update directly through HACS fails as well.

Clicking the update hint in the HACS start page does simply nothing. When I go deeper into "Integrations" and click the "Matter (Environmental)" tile I get to a page which states "Unknown error".

I guess this is a kind of deadlock as obviously the old version 0.3.0 is missing something (manifest.json?) that HACS needs to handle it.

**Comment by balloob** [comment]
The custom integration has been removed and will be available in the 2022.12.0 beta 1 release

**Comment by Jpsy** [comment]
Thanks Paulus.
Any hints how to remove it from HACS?

**Comment by lcnittl** [comment]
> Thanks Paulus. Any hints how to remove it from HACS?

Hi @Jpsy, I was able to remove it by going to "Custom repositories" (three dot menu top right) and then trashing the repo entry.

**Comment by denniswham** [comment]
> Hi @Jpsy, I was able to remove it by going to "Custom repositories" (three dot menu top right) and then trashing the repo entry.

And to be complete, you can remove the Matter Experimental folder from the custom_components folder in your config.

**Comment by agners** [comment]
@ludeeus do you happen to know how to remove it from HACS in this case? 😅

**Comment by ludeeus** [comment]
As described 👆

**Comment by Wirrkopf76** [comment]
I have removed the repo from HACS and restarted HomeAssistant. After that I have removed the  folder matter_experimental under custom_components. Unfortunately I seem to have missed a step. Every time I restart Home Assistant I get an error: 

`2022-12-01 17:34:13.358 ERROR (MainThread) [homeassistant.config_entries] Cannot find integration matter
2022-12-01 17:34:13.398 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 799, in async_create_flow
integration = await loader.async_get_integration(self.hass, handler_key)
File "/usr/src/homeassistant/homeassistant/loader.py", line 774, in async_get_integration
raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'matter' not found.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 802, in async_create_flow
raise data_entry_flow.UnknownHandler from err
homeassistant.data_entry_flow.UnknownHandler`

**Comment by Wirrkopf76** [comment]
I have solved it myself. I have deleted the config part related to Matter (experimental) in config/.storage/core.config_entries and after that the error went away.

**Comment by lcnittl** [comment]
Was the integration still installed? (under `/config/integrations`)

**Comment by Wirrkopf76** [comment]
I don't have the folder or file /config/integrations, but like I said, I have deleted the config_entry and now all is good.

**Comment by lcnittl** [comment]
Sorry for having been unclear: This is the URL path ```http://homeassistant.lan:8123/config/integrations```

But great that you fixed it in any case!

**Comment by LordNex** [comment]
Same issue here. I was able to disable the add on so the update doesn’t show up anymore but I can’t uninstall the HACS integration

**Comment by Grey-Lancaster** [comment]
> The custom integration has been removed and will be available in the 2022.12.0 beta 1 release

Wish I had found this 3 days ago LOL

So do I need to delete the matter folder under hcas or just wait for the next build?
Thanks
Grey

**Comment by FrankNa88** [comment]
Hi guys, 

I didn't get very well what to do.
I got  this error:
![Screenshot_20240121-163303](https://github.com/home-assistant-libs/python-matter-server/assets/33216135/32f5d5a7-510d-452e-85a7-cd7fa4ac00af)
Could you please specify exactly what to remove and where

Thank you very much in advance

**Comment by Grey-Lancaster** [comment]
you do not use HACS anymore it's in the regular add-on store

**Comment by FrankNa88** [comment]
Yes I have in my integrations but I cannot update Ii due to this error
