### ISSUE TITLE
ValueError: Unknown level: 'NULL'

### ISSUE THREAD

**Issue by Ulrar** [home-assistant-libs/python-matter-server#133]
It looks like the latest docker image isn't starting correctly : 

```
[14:16:22] INFO: Starting Matter Server...
curl: (6) Could not resolve host: supervisor
[14:16:22] ERROR: Something went wrong contacting the API
curl: (6) Could not resolve host: supervisor
[14:16:23] ERROR: Something went wrong contacting the API
curl: (6) Could not resolve host: supervisor
[14:16:23] ERROR: Something went wrong contacting the API
[14:16:23] INFO: Successfully send discovery information to Home Assistant.
Traceback (most recent call last):
  File "/usr/local/bin/matter-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/__main__.py", line 72, in main
    logging.basicConfig(handlers=handlers, level=args.log_level.upper())
  File "/usr/lib/python3.9/logging/__init__.py", line 2018, in basicConfig
    root.setLevel(level)
  File "/usr/lib/python3.9/logging/__init__.py", line 1417, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python3.9/logging/__init__.py", line 194, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'NULL'
```

**Comment by marcelveldt** [comment]
Are you running the docker image directly, bypassing HAOS ?
Because we did not specifically account for that and the current docker image is meant to be used for the Matter add-on

**Comment by Ulrar** [comment]
That's right yes, it's just a container running next to HA, it's not HAOS

**Comment by marcelveldt** [comment]
Well, the docker image is not meant to be used standalone as it is created for the Home Assistant supervisor. For example that is where the config file is provided from. It maybe works by accident today and breaks tomorrow. Best is to create a dedicated docker image to run standalone.

At this time we are really busy with the basic stuff and polishing the Matter server and integration for daily usage, focusing on the add-on as first step and we might provide a standalone container later but if you want to pick up the glove, you can look at the add-on structure to find out what's missing for the standalone container.
