### ISSUE TITLE
CHIP Error 0x0000002F: Invalid argument during commission_on_network

### ISSUE THREAD

**Issue by Muzach** [home-assistant-libs/python-matter-server#140]
```
2022-12-16 10:48:02 core-matter-server matter_server.server.client_handler[124] ERROR [548283895664] Error handling message: CommandMessage(message_id='9b817f02d5444abe9e4ec7b7d95480c8', command='commission_on_network', args={'setup_pin_code': 5284714089})
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/client_handler.py", line 183, in _run_handler
    result = await result
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 164, in commission_on_network
    raise NodeCommissionFailed(f"CommissionWithCode failed for node {node_id}")
matter_server.common.models.error.NodeCommissionFailed: CommissionWithCode failed for node 7
2022-12-16 10:48:02 core-matter-server asyncio[124] ERROR Task exception was never retrieved
future: <Task finished name='Task-4950' coro=<StorageController.async_save() done, defined at /usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py:136> exception=ChipStackError(47, 'CHIP Error 0x0000002F: Invalid argument')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py", line 151, in async_save
    await self.server.loop.run_in_executor(None, do_save)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py", line 140, in do_save
    filename_backup = f"{self.filename}.backup"
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py", line 32, in filename
    f"{self.server.device_controller.compressed_fabric_id}.json",
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 67, in compressed_fabric_id
    return self.chip_controller.GetCompressedFabricId()
  File "/usr/local/lib/python3.9/dist-packages/chip/ChipDeviceCtrl.py", line 777, in GetCompressedFabricId
    raise self._ChipStack.ErrorToException(res)
chip.exceptions.ChipStackError: CHIP Error 0x0000002F: Invalid argument
2022-12-16 10:49:10 core-matter-server chip.TOO[124] INFO Discovered Device: fd24:a090:cec:0:46d6:9a8c:852a:ff5a:5540
2022-12-16 10:49:10 core-matter-server matter_server.server.client_handler[124] ERROR [548283892688] Error handling message: CommandMessage(message_id='282746bd7c82460facd12bbcce84585f', command='commission_on_network', args={'setup_pin_code': 5284714089})
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/client_handler.py", line 183, in _run_handler
    result = await result
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 164, in commission_on_network
    raise NodeCommissionFailed(f"CommissionWithCode failed for node {node_id}")
matter_server.common.models.error.NodeCommissionFailed: CommissionWithCode failed for node 8
2022-12-16 10:49:10 core-matter-server asyncio[124] ERROR Task exception was never retrieved
future: <Task finished name='Task-4958' coro=<StorageController.async_save() done, defined at /usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py:136> exception=ChipStackError(47, 'CHIP Error 0x0000002F: Invalid argument')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py", line 151, in async_save
    await self.server.loop.run_in_executor(None, do_save)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py", line 140, in do_save
    filename_backup = f"{self.filename}.backup"
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/storage.py", line 32, in filename
    f"{self.server.device_controller.compressed_fabric_id}.json",
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 67, in compressed_fabric_id
    return self.chip_controller.GetCompressedFabricId()
  File "/usr/local/lib/python3.9/dist-packages/chip/ChipDeviceCtrl.py", line 777, in GetCompressedFabricId
    raise self._ChipStack.ErrorToException(res)
chip.exceptions.ChipStackError: CHIP Error 0x0000002F: Invalid argument
```

**Comment by marcelveldt** [comment]
Yes, we are aware of this issue and investigating it.

**Comment by marcelveldt** [comment]
The issue in our code is fixed for "commission_on_network" but it seems the command itself is still not very reliable as I am yet unable to see it working in action. Please try again when we release a new version of the Matter server with the SDK version bumped to 2023.2.1, this will be released next Wednesday (together with HA beta)

**Comment by flatsiedatsie** [comment]
Perhaps of interest: I just saw this error with `commission_with_code`, but right before that I saw `ERROR:chip.CTL:Wifi credentials are too large`. I was trying to see if I could use the secure PSK value instead of the actual password, so I wouldn't have to store the actual password in my project. But it seems the plain-text password is required.

```
DEBUG:matter_server.server.client_handler:[548137132080] Handling command commission_with_code
ERROR:chip.CTL:Wifi credentials are too large
...
client: on_message: {
  "message_id": "commission_with_code",
  "error_code": 3,
  "details": "../src/controller/AutoCommissioner.cpp:95: CHIP Error 0x0000002F: Invalid argument",
  "_type": "matter_server.common.models.message.ErrorResultMessage"
}
```
