### ISSUE TITLE
Unable to commission ESP32 device

### ISSUE THREAD

**Issue by baylf2000** [home-assistant-libs/python-matter-server#144]
I've been struggling for days now to try and commission a single device using the HA integration, which seems completely unable to communicate with the HA server addon no matter what I do, so I switched to trying to communicate with the server addon using WS. I have been able to successfully commission the ESP32 device using the Android app, and I have always erased and reflashed the ESP32 device before attempting to commission it again using the HA addon.

I use the following WS command:
```
{ "message_id": "3", "command": "commission_with_code", "args": { "code": "MT:Y.K9042C00KA0648G00" } }
```

and get the following error:
```
{ "message_id": "3", "error_code": 99, "details": "Failed to interview node 18", "_type": "matter_server.common.models.message.ErrorResultMessage" }
```

And here are the logs from the HA server:
```
2022-12-20 17:48:54 core-matter-server matter_server.server.client_handler[124] DEBUG [140132372786672] Received CommandMessage(message_id='3', command='commission_with_code', args={'code': 'MT:Y.K9042C00KA0648G00'})
2022-12-20 17:48:54 core-matter-server matter_server.server.client_handler[124] DEBUG [140132372786672] Handling command commission_with_code
2022-12-20 17:48:54 core-matter-server chip.CTL[124] INFO Setting wifi credentials from parameters
2022-12-20 17:48:54 core-matter-server chip.CTL[124] INFO Setting attestation nonce to random value
2022-12-20 17:48:54 core-matter-server chip.CTL[124] INFO Setting CSR nonce to random value
2022-12-20 17:48:54 core-matter-server chip.CTL[124] DEBUG Stopping commissioning discovery over DNS-SD
2022-12-20 17:48:54 core-matter-server chip.CTL[124] INFO Starting commissioning discovery over BLE
2022-12-20 17:48:54 core-matter-server chip.CTL[124] INFO Starting commissioning discovery over DNS-SD
2022-12-20 17:48:54 core-matter-server chip.BLE[124] INFO BLE removing known devices.
2022-12-20 17:48:57 core-matter-server chip.BLE[124] INFO BLE initiating scan.
2022-12-20 17:48:57 core-matter-server chip.DL[124] ERROR Long dispatch time: 2054 ms, for event type 2
2022-12-20 17:48:57 core-matter-server chip.BLE[124] INFO New device scanned: DE:77:91:4D:CB:DE
2022-12-20 17:48:57 core-matter-server chip.BLE[124] INFO Device discriminator match. Attempting to connect.
2022-12-20 17:48:57 core-matter-server chip.BLE[124] INFO Scan complete notification without an active scan.
2022-12-20 17:48:57 core-matter-server chip.DL[124] DEBUG Bluez disconnected
2022-12-20 17:48:57 core-matter-server chip.DL[124] INFO Bluez notify CHIPoBluez connection disconnected
2022-12-20 17:48:57 core-matter-server chip.DL[124] ERROR FAIL: ConnectDevice : GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
 (41)
2022-12-20 17:48:57 core-matter-server chip.DL[124] DEBUG HandlePlatformSpecificBLEEvent 16386
2022-12-20 17:48:57 core-matter-server chip.CTL[124] ERROR Commissioning discovery over BLE failed: ../src/platform/Linux/bluez/Helper.cpp:1775: CHIP Error 0x000000AC: Internal error
2022-12-20 17:48:57 core-matter-server chip.-[124] ERROR ../src/platform/Linux/bluez/Helper.cpp:1775: CHIP Error 0x000000AC: Internal error at ../src/controller/SetUpCodePairer.cpp:283
2022-12-20 17:48:57 core-matter-server matter_server.server.storage[124] DEBUG Saved data to persistent storage
2022-12-20 17:49:24 core-matter-server chip.CTL[124] ERROR Discovery timed out
2022-12-20 17:49:24 core-matter-server chip.CTL[124] DEBUG Stopping commissioning discovery over DNS-SD
2022-12-20 17:49:27 core-matter-server chip.DIS[124] ERROR Timeout waiting for mDNS resolution.
2022-12-20 17:49:57 core-matter-server matter_server.server.device_controller[124] DEBUG Interviewing node: 18
2022-12-20 17:49:57 core-matter-server chip.CSM[124] DEBUG FindOrEstablishSession: PeerId = [1:0000000000000012]
2022-12-20 17:49:57 core-matter-server chip.CSM[124] DEBUG FindOrEstablishSession: No existing OperationalSessionSetup instance found
2022-12-20 17:49:57 core-matter-server chip.CTL[124] DEBUG OperationalSessionSetup[1:0000000000000012]: State change 1 --> 2
2022-12-20 17:49:57 core-matter-server chip.DIS[124] INFO Checking node lookup status after 201 ms
2022-12-20 17:50:12 core-matter-server chip.DIS[124] INFO Checking node lookup status after 15001 ms
2022-12-20 17:50:12 core-matter-server chip.DIS[124] ERROR OperationalSessionSetup[1:0000000000000012]: operational discovery failed: ../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:174: CHIP Error 0x00000032: Timeout
2022-12-20 17:50:12 core-matter-server matter_server.server.client_handler[124] ERROR [140132372786672] Error handling message: CommandMessage(message_id='3', command='commission_with_code', args={'code': 'MT:Y.K9042C00KA0648G00'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 238, in interview_node
    await self._call_sdk(self.chip_controller.ResolveNode, nodeid=node_id)
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 397, in _call_sdk
    return await self.server.loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/chip/ChipDeviceCtrl.py", line 595, in ResolveNode
    self.GetConnectedDeviceSync(nodeid, allowPASE=False)
  File "/usr/local/lib/python3.9/dist-packages/chip/ChipDeviceCtrl.py", line 859, in GetConnectedDeviceSync
    raise self._ChipStack.ErrorToException(returnErr)
chip.exceptions.ChipStackError: CHIP Error 0x00000032: Timeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/client_handler.py", line 183, in _run_handler
    result = await result
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 134, in commission_with_code
    await self.interview_node(node_id)
  File "/usr/local/lib/python3.9/dist-packages/matter_server/server/device_controller.py", line 245, in interview_node
    raise NodeInterviewFailed(f"Failed to interview node {node_id}") from err
matter_server.common.models.error.NodeInterviewFailed: Failed to interview node 18
2022-12-20 17:50:28 core-matter-server chip.DIS[124] ERROR Timeout waiting for mDNS resolution.
```

**Comment by marcelveldt** [comment]
The bluetooth comissioning is failing, most probably because the bluetooth adapter is already occupied by the bluetooth integration
