### ISSUE TITLE
pypi.org page is lacking updated information

### ISSUE THREAD

**Issue by guyluz11** [home-assistant-libs/python-matter-server#171]
There are several missing and old information on readme and pypi.org  pages

First of all the [pypi.org](https://pypi.org/project/python-matter-server) page is missing a link to this repo

![image](https://user-images.githubusercontent.com/9304740/212568649-d6e5b9cc-2f8d-4246-a73d-443b9af95ae7.png)

Second there are several places in the readme that says the old name `chip` and didn't got updated to the new name `matter`.

Third the command `python -m matter_server.server` does not work for me, maybe I am missing something.
Getting the error 
```python
python -m matter_server.server
/usr/bin/python: No module named matter_server
```

**Comment by kjagiello** [comment]
> Third the command `python -m matter_server.server` does not work for me, maybe I am missing something.
Getting the error

Are you sure you have installed this package? I set it up yesterday and can successfully boot up the server using that command.

**Comment by marcelveldt** [comment]
The upstream sdk is still named project chip, hence the name

**Comment by guyluz11** [comment]
> > Third the command `python -m matter_server.server` does not work for me, maybe I am missing something.
> > Getting the error
> 
> Are you sure you have installed this package? I set it up yesterday and can successfully boot up the server using that command.

My bad, I run it on python (python2) and not on python3 so it got confused.

I am getting a different error now 


 ```python
INFO Initializing CHIP/Matter Controller Stack...
[1674064152.017892][8595:8595] CHIP:CTL: Setting attestation nonce to random value
[1674064152.019712][8595:8595] CHIP:CTL: Setting CSR nonce to random value
[1674064152.024594][8595:8595] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1674064152.024714][8595:8595] CHIP:DL: writing settings to file (/tmp/chip_kvs-FjN1PO)
[1674064152.024766][8595:8595] CHIP:DL: renamed tmp file to file (/tmp/chip_kvs)
[1674064152.024836][8595:8595] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1674064152.024849][8595:8595] CHIP:DL: failed to open file (/data/chip_factory.ini-h1JPBd) for writing
[1674064152.024858][8595:8595] CHIP:DL: Configuration Manager initialization failed: ../src/platform/Linux/CHIPLinuxStorageIni.cpp:122: CHIP Error 0x000000AD: Open file failed
2023-01-18 19:49:12 myUserName-comp PersistentStorage[8595] WARNING Initializing persistent storage from file: /home/myUserName/.matter_server/chip.json
2023-01-18 19:49:12 myUserName-comp root[8595] ERROR [Errno 2] No such file or directory: '/home/myUserName/.matter_server/chip.json'
2023-01-18 19:49:12 myUserName-comp root[8595] CRITICAL Could not load configuration from /home/myUserName/.matter_server/chip.json - resetting configuration...
2023-01-18 19:49:12 myUserName-comp root[8595] WARNING No valid SDK configuration present - clearing out configuration
2023-01-18 19:49:12 myUserName-comp root[8595] WARNING No valid REPL configuration present - clearing out configuration
2023-01-18 19:49:12 myUserName-comp chip.DL[8595] ERROR ChipLinuxStorage::Init: Attempt to re-initialize with KVS config file: /tmp/chip_kvs
2023-01-18 19:49:12 myUserName-comp chip.DL[8595] ERROR SystemLayer initialization failed: ../src/system/SystemLayerImplSelect.cpp:45: CHIP Error 0x00000003: Incorrect state
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/myUserName/Documents/git/python-matter-server/matter_server/server/__main__.py", line 92, in <module>
    main()
  File "/home/myUserName/Documents/git/python-matter-server/matter_server/server/__main__.py", line 79, in main
    server = MatterServer(
  File "/home/myUserName/Documents/git/python-matter-server/matter_server/server/server.py", line 69, in __init__
    self.stack = MatterStack(self)
  File "/home/myUserName/Documents/git/python-matter-server/matter_server/server/stack.py", line 32, in __init__
    self._chip_stack = ChipStack(
  File "/home/myUserName/.local/lib/python3.10/site-packages/chip/ChipStack.py", line 67, in wrapper
    instance[0] = cls(*args, **kwargs)
  File "/home/myUserName/.local/lib/python3.10/site-packages/chip/ChipStack.py", line 273, in __init__
    raise self.ErrorToException(res)
chip.exceptions.ChipStackError: CHIP Error 0x00000003: Incorrect state
Exception ignored in: <function PersistentStorage.__del__ at 0x7f00cee85990>
Traceback (most recent call last):
  File "/home/myUserName/.local/lib/python3.10/site-packages/chip/storage/__init__.py", line 262, in __del__
AttributeError: module 'builtins' has no attribute 'chipStack'
Segmentation fault (core dumped)

```

I probably doing something wrong so will just try couple of things.

**Comment by guyluz11** [comment]
What about adding a link to the repo in pypi page?
