### ISSUE TITLE
AbstractMatterNodeDevice class method device_info is returning None instead of Clusters.Basic or Clusters.BridgedDeviceBasic

### ISSUE THREAD

**Issue by ArturoGuerra** [home-assistant-libs/python-matter-server#180]
![Error](https://i.arturonet.com/XhUjSF29Wn.png)

This error seems to be related to chip.clusters.Objects.Basic not existing so when the get_cluster function runs it doesn't find anything

**Comment by ArturoGuerra** [comment]
Just some extra info on this issue I don't know if this behavior happens when querying a native matter device or just a matter bridge device cuz in this particular case I'm using the hue bridge.

**Comment by MartinHjelmare** [comment]
Can you paste the log instead of attaching an image? Thanks!

**Comment by ArturoGuerra** [comment]
```
2023-01-26 07:38:30.018 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of python-matter-server==2.0.1
2023-01-26 07:38:40.768 INFO (MainThread) [matter_server.client.connection] Connected to Matter Fabric 1 (17429810890900546008), Schema version 1, CHIP SDK Version 2023.1.0
2023-01-26 07:38:40.768 INFO (MainThread) [homeassistant.setup] Setting up matter
2023-01-26 07:38:40.768 INFO (MainThread) [homeassistant.setup] Setup of domain matter took 0.0 seconds
2023-01-26 07:38:40.773 INFO (MainThread) [matter_server.client.connection] Connected to Matter Fabric 1 (17429810890900546008), Schema version 1, CHIP SDK Version 2023.1.0
2023-01-26 07:38:40.778 INFO (MainThread) [matter_server.client] Matter client initialized.
2023-01-26 07:38:40.781 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.matter
2023-01-26 07:38:40.783 INFO (SyncWorker_0) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2023-01-26 07:38:40.784 INFO (SyncWorker_3) [homeassistant.loader] Loaded light from homeassistant.components.light
2023-01-26 07:38:40.785 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2023-01-26 07:38:40.785 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds
2023-01-26 07:38:40.788 INFO (MainThread) [homeassistant.setup] Setting up light
2023-01-26 07:38:40.789 INFO (SyncWorker_4) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2023-01-26 07:38:40.790 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.matter
2023-01-26 07:38:40.794 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.0 seconds
2023-01-26 07:38:40.798 INFO (MainThread) [homeassistant.setup] Setting up switch
2023-01-26 07:38:40.798 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.0 seconds
2023-01-26 07:38:40.801 INFO (MainThread) [homeassistant.components.light] Setting up light.matter
2023-01-26 07:38:40.805 INFO (MainThread) [homeassistant.components.switch] Setting up switch.matter
2023-01-26 07:39:10.867 ERROR (MainThread) [homeassistant.components.matter] Unexpected exception: 'NoneType' object has no attribute 'nodeLabel'
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/components/matter/__init__.py", line 131, in _client_listen
    await matter_client.start_listening(init_ready)
  File "/home/vscode/.local/lib/python3.9/site-packages/matter_server/client/client.py", line 282, in start_listening
    self._handle_incoming_message(msg)
  File "/home/vscode/.local/lib/python3.9/site-packages/matter_server/client/client.py", line 323, in _handle_incoming_message
    self._handle_event_message(msg)
  File "/home/vscode/.local/lib/python3.9/site-packages/matter_server/client/client.py", line 338, in _handle_event_message
    self._signal_event(EventType.NODE_ADDED, node)
  File "/home/vscode/.local/lib/python3.9/site-packages/matter_server/client/client.py", line 369, in _signal_event
    callback(event, data)
  File "/workspaces/core/homeassistant/components/matter/adapter.py", line 61, in node_added_callback
    self._setup_node(node)
  File "/workspaces/core/homeassistant/components/matter/adapter.py", line 80, in _setup_node
    self._create_device_registry(bridge_device)
  File "/workspaces/core/homeassistant/components/matter/adapter.py", line 98, in _create_device_registry
    name = basic_info.nodeLabel
AttributeError: 'NoneType' object has no attribute 'nodeLabel'
2023-01-26 07:39:10.909 INFO (MainThread) [matter_server.client.connection] Connected to Matter Fabric 1 (17429810890900546008), Schema version 1, CHIP SDK Version 2023.1.0
2023-01-26 07:39:11.338 INFO (MainThread) [matter_server.client] Matter client initialized.
2023-01-26 07:39:11.338 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.matter
2023-01-26 07:39:11.338 INFO (MainThread) [homeassistant.components.light] Setting up light.matter
2023-01-26 07:39:11.338 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.matter
2023-01-26 07:39:11.339 INFO (MainThread) [homeassistant.components.switch] Setting up switch.matter
2023-01-26 07:39:11.339 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Matter for matter
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/workspaces/core/homeassistant/components/matter/__init__.py", line 109, in async_setup_entry
    await matter.setup_nodes()
  File "/workspaces/core/homeassistant/components/matter/adapter.py", line 53, in setup_nodes
    self._setup_node(node)
  File "/workspaces/core/homeassistant/components/matter/adapter.py", line 80, in _setup_node
    self._create_device_registry(bridge_device)
  File "/workspaces/core/homeassistant/components/matter/adapter.py", line 98, in _create_device_registry
    name = basic_info.nodeLabel
AttributeError: 'NoneType' object has no attribute 'nodeLabel'
```

**Comment by MartinHjelmare** [comment]
I think we need to update the models to use `clusters.BasicInformation` instead of `clusters.Basic` as that was renamed to `clusters.BasicInformation`

Here:

https://github.com/home-assistant-libs/python-matter-server/blob/f353c273ed7213f18931b2dfed908fb6529c2ec6/matter_server/common/models/node_device.py#L25-L47

https://github.com/home-assistant-libs/python-matter-server/blob/f353c273ed7213f18931b2dfed908fb6529c2ec6/matter_server/common/models/node.py#L200-L218

**Comment by MartinHjelmare** [comment]
It would be great to get a diagnostics dump from the bridge device as we're lacking tests for bridge devices. :+1:

**Comment by MartinHjelmare** [comment]
We can dump diagnostics from Home Assistant when running core-2023.2.0b0+. Dump the diagnostics of the config entry and all the commissioned nodes will be included.

**Comment by ArturoGuerra** [comment]
Oh okay I'll do that in the morning

**Comment by ArturoGuerra** [comment]
I was trying to dump the diagnostics and it appears the NoneType error is still there in some cases, it looks like its only happening on the bridge device itself now and not on all bridged devices.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/matter/__init__.py", line 109, in async_setup_entry
    await matter.setup_nodes()
  File "/usr/src/homeassistant/homeassistant/components/matter/adapter.py", line 53, in setup_nodes
    self._setup_node(node)
  File "/usr/src/homeassistant/homeassistant/components/matter/adapter.py", line 80, in _setup_node
    self._create_device_registry(bridge_device)
  File "/usr/src/homeassistant/homeassistant/components/matter/adapter.py", line 98, in _create_device_registry
    name = basic_info.nodeLabel
AttributeError: 'NoneType' object has no attribute 'nodeLabel'
```
