### ISSUE TITLE
Getting ColorControl cluster causes a TypeError

### ISSUE THREAD

**Issue by ArturoGuerra** [home-assistant-libs/python-matter-server#187]
Using the `MatterDeviceTypeInstance.get_cluster` method with the `ColorControl` cluster causes a TypeError

```
Traceback (most recent call last):
  File "/home/arturo/python-matter-server-testing/clusterissue.py", line 67, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/arturo/python-matter-server-testing/clusterissue.py", line 62, in main
    await adapter.setup_nodes()
  File "/home/arturo/python-matter-server-testing/clusterissue.py", line 26, in setup_nodes
    await self.setup_node(node)
  File "/home/arturo/python-matter-server-testing/clusterissue.py", line 49, in setup_node
    cluster = instance.get_cluster(Clusters.ColorControl)
  File "/home/arturo/python-matter-server-testing/venv/lib/python3.10/site-packages/matter_server/common/models/device_type_instance.py", line 63, in get_cluster
    return self.node.get_cluster(self.endpoint, cluster)
  File "/home/arturo/python-matter-server-testing/venv/lib/python3.10/site-packages/matter_server/common/models/node.py", line 196, in get_cluster
    return dataclass_from_dict(
  File "/home/arturo/python-matter-server-testing/venv/lib/python3.10/site-packages/matter_server/common/helpers/util.py", line 226, in dataclass_from_dict
    **{
  File "/home/arturo/python-matter-server-testing/venv/lib/python3.10/site-packages/matter_server/common/helpers/util.py", line 227, in <dictcomp>
    field.name: parse_value(
  File "/home/arturo/python-matter-server-testing/venv/lib/python3.10/site-packages/matter_server/common/helpers/util.py", line 170, in parse_value
    raise TypeError(err)
TypeError: Value {'TLVValue': None, 'Reason': None} of type <class 'dict'> is invalid for ColorControl.numberOfPrimaries, expected value of type typing.Union[chip.clusters.Types.Nullable, chip.tlv.uint]
```

**Comment by ArturoGuerra** [comment]
Seems like its an issue with this https://github.com/home-assistant-libs/python-matter-server/blob/6d38b82b6cd1103e1832808c8caf165d0ad079fe/matter_server/common/helpers/util.py#L62-L89

**Comment by ArturoGuerra** [comment]
After looking into it, it appears this is not a bug with the matter server but a bug with the Philips Hue Bridge, now how do we want to handle this by erroring out or throwing a warning like the python matter cli does?

```
ReadResponse(
│   attributes={
│   │   2: {
│   │   │   <class 'chip.clusters.Objects.ColorControl'>: {
│   │   │   │   <class 'chip.clusters.Attribute.DataVersion'>: 3048281882,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.CurrentHue'>: 160,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.CurrentX'>: 21934,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.CurrentY'>: 22760,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorTemperatureMireds'>: 185,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.CurrentSaturation'>: 52,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.EnhancedCurrentHue'>: 40986,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorMode'>: 2,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.Options'>: 0,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.EnhancedColorMode'>: 2,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorLoopActive'>: ValueDecodeFailure(
│   │   │   │   │   TLVValue=None,
│   │   │   │   │   Reason=InteractionModelError(<Status.UnsupportedAttribute: 134>)
│   │   │   │   ),
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorLoopDirection'>: ValueDecodeFailure(
│   │   │   │   │   TLVValue=None,
│   │   │   │   │   Reason=InteractionModelError(<Status.UnsupportedAttribute: 134>)
│   │   │   │   ),
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorLoopTime'>: ValueDecodeFailure(
│   │   │   │   │   TLVValue=None,
│   │   │   │   │   Reason=InteractionModelError(<Status.UnsupportedAttribute: 134>)
│   │   │   │   ),
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorLoopStartEnhancedHue'>: ValueDecodeFailure(
│   │   │   │   │   TLVValue=None,
│   │   │   │   │   Reason=InteractionModelError(<Status.UnsupportedAttribute: 134>)
│   │   │   │   ),
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorLoopStoredEnhancedHue'>: ValueDecodeFailure(
│   │   │   │   │   TLVValue=None,
│   │   │   │   │   Reason=InteractionModelError(<Status.UnsupportedAttribute: 134>)
│   │   │   │   ),
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorCapabilities'>: 25,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.NumberOfPrimaries'>: ValueDecodeFailure(
│   │   │   │   │   TLVValue=None,
│   │   │   │   │   Reason=InteractionModelError(<Status.UnsupportedAttribute: 134>)
│   │   │   │   ),
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorTempPhysicalMinMireds'>: 153,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ColorTempPhysicalMaxMireds'>: 500,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.CoupleColorTempToLevelMinMireds'>: 250,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.StartUpColorTemperatureMireds'>: 65535,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.RemainingTime'>: 0,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.FeatureMap'>: 25,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.ClusterRevision'>: 5,
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.GeneratedCommandList'>: [],
│   │   │   │   <class 'chip.clusters.Objects.ColorControl.Attributes.AcceptedCommandList'>: [
│   │   │   │   │   0,
│   │   │   │   │   1,
│   │   │   │   │   2,
```

**Comment by ArturoGuerra** [comment]
Was thinking we could use the same ValueDecodeFailure type and return that instead of outright erroring out
