### ISSUE TITLE
can not run python matter server

### ISSUE THREAD

**Issue by typzzh** [home-assistant-libs/python-matter-server#204]
###############python3.9  -m matter_server.server
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/trex/.local/lib/python3.9/site-packages/matter_server/server/__init__.py", line 3, in <module>
    from .server import MatterServer
  File "/home/trex/.local/lib/python3.9/site-packages/matter_server/server/server.py", line 20, in <module>
    from ..server.client_handler import WebsocketClientHandler
  File "/home/trex/.local/lib/python3.9/site-packages/matter_server/server/client_handler.py", line 12, in <module>
    from chip.exceptions import ChipStackError
ModuleNotFoundError: No module named 'chip.exceptions'

**Comment by flatsiedatsie** [comment]
Here's an example of how I got it to run.

```
python3.9 -m pip install \
    python-matter-server[server] \
    home_assistant_chip_clusters \
    home_assistant_chip_core \
    home_assistant_chip_repl
```
The repl may not be needed, I'm not sure.

If you want to check a working implementation (outside of Home Assistant itself):
https://github.com/createcandle/matter-adapter/blob/9ab547b230e886513eb0d32520bbcee74d868fa7/package.sh#L155
https://github.com/createcandle/matter-adapter/blob/9ab547b230e886513eb0d32520bbcee74d868fa7/.github/workflows/release.yml#L73
