### ISSUE TITLE
`python3 -m matter_server.server` crashes with Segmentation Fault

### ISSUE THREAD

**Issue by sirtux** [home-assistant-libs/python-matter-server#235]
Hello,
I'm trying to run 3.1.0 on a raspberrry with python3.10/3.11 (both tried),
however it crashed in the end with a Segmentation Fault:

```
matter@ha:~$ python3 -m matter_server.server
2023-03-16 12:39:53 ha matter_server.server.stack[8363] INFO Initializing CHIP/Matter Controller Stack...
[1678970393.586951][8363:8363] CHIP:CTL: Setting attestation nonce to random value
[1678970393.587309][8363:8363] CHIP:CTL: Setting CSR nonce to random value
[1678970393.588764][8363:8363] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1678970393.589068][8363:8363] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1678970393.589206][8363:8363] CHIP:DL: failed to open file (/data/chip_factory.ini-rmmMfQ) for writing
[1678970393.589289][8363:8363] CHIP:DL: Configuration Manager initialization failed: ../src/platform/Linux/CHIPLinuxStorageIni.cpp:122: CHIP Error 0x000000AD: Open file failed
2023-03-16 12:39:53 ha PersistentStorage[8363] WARNING Initializing persistent storage from file: /opt/matter/.matter_server/chip.json
2023-03-16 12:39:53 ha root[8363] ERROR [Errno 2] No such file or directory: '/opt/matter/.matter_server/chip.json'
2023-03-16 12:39:53 ha root[8363] CRITICAL Could not load configuration from /opt/matter/.matter_server/chip.json - resetting configuration...
2023-03-16 12:39:53 ha root[8363] WARNING No valid SDK configuration present - clearing out configuration
2023-03-16 12:39:53 ha root[8363] WARNING No valid REPL configuration present - clearing out configuration
2023-03-16 12:39:53 ha chip.DL[8363] ERROR ChipLinuxStorage::Init: Attempt to re-initialize with KVS config file: /tmp/chip_kvs
2023-03-16 12:39:53 ha chip.DL[8363] ERROR SystemLayer initialization failed: ../src/system/SystemLayerImplSelect.cpp:45: CHIP Error 0x00000003: Incorrect state
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/matter/lib/python3.10/site-packages/matter_server/server/__main__.py", line 92, in <module>
    main()
  File "/opt/matter/lib/python3.10/site-packages/matter_server/server/__main__.py", line 79, in main
    server = MatterServer(
  File "/opt/matter/lib/python3.10/site-packages/matter_server/server/server.py", line 73, in __init__
    self.stack = MatterStack(self)
  File "/opt/matter/lib/python3.10/site-packages/matter_server/server/stack.py", line 32, in __init__
    self._chip_stack = ChipStack(
  File "/opt/matter/lib/python3.10/site-packages/chip/ChipStack.py", line 68, in wrapper
    instance[0] = cls(*args, **kwargs)
  File "/opt/matter/lib/python3.10/site-packages/chip/ChipStack.py", line 273, in __init__
    res.raise_on_error()
  File "/opt/matter/lib/python3.10/site-packages/chip/native/__init__.py", line 66, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: ../src/system/SystemLayerImplSelect.cpp:45: CHIP Error 0x00000003: Incorrect state
Segmentation fault (core dumped)
```

Installed package versions:
```
matter@ha:~$ pip list
Package                      Version
---------------------------- ---------
aiohttp                      3.8.4
aiorun                       2022.11.1
aiosignal                    1.3.1
asttokens                    2.2.1
async-timeout                4.0.2
attrs                        22.2.0
backcall                     0.2.0
charset-normalizer           3.1.0
coloredlogs                  15.0.1
construct                    2.10.68
dacite                       1.8.0
decorator                    5.1.1
deprecation                  2.1.0
executing                    1.2.0
frozenlist                   1.3.3
home-assistant-chip-clusters 2023.2.2
home-assistant-chip-core     2023.2.2
humanfriendly                10.0
idna                         3.4
ipdb                         0.13.13
ipython                      8.11.0
jedi                         0.18.2
markdown-it-py               2.2.0
matplotlib-inline            0.1.6
mdurl                        0.1.2
mobly                        1.12.1
multidict                    6.0.4
orjson                       3.8.7
packaging                    23.0
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
pip                          23.0.1
portpicker                   1.5.2
prompt-toolkit               3.0.38
psutil                       5.9.4
ptyprocess                   0.7.0
pure-eval                    0.2.2
Pygments                     2.14.0
python-matter-server         3.1.0
PyYAML                       6.0
rich                         13.3.2
setuptools                   59.6.0
six                          1.16.0
stack-data                   0.6.2
tomli                        2.0.1
traitlets                    5.9.0
wcwidth                      0.2.6
wheel                        0.40.0
yarl                         1.8.2
```

I guess it is an upstream issue in the SDK, but I have no idea what I should give them as a report...

Any help is appreciated,
Thanks,
Tom

**Comment by hidaris** [comment]
Have you seen complaints related to the openssl version?

**Comment by sirtux** [comment]
Not really, using libssl1.1_1.1.1n-0+deb11u3.

I'm currently trying to reproduce it with a docker container to have a clean environment,
but the current Dockerfile doesn't build, and will have hopefully a PR for that later on.

**Comment by sirtux** [comment]
It works within the docker environment, so I assume it is some weird openssl library thing,
I'll close therefore this issue.

**Comment by MartinHjelmare** [comment]
The storage directory currently needs to be at `/data`. It's hardcoded in the chip SDK wheels we use. So the server needs to be started with the storage path set to `/data`.

I think that's the issue from looking at your log.
