### ISSUE TITLE
Failed to commission latest light example from esp-matter

### ISSUE THREAD

**Issue by Diegorro98** [home-assistant-libs/python-matter-server#255]
Hi,
I was trying to commissioning the ligth example from the esp-matter repo, but I can't do it to Home Assistant.
I'm able to commissioning the esp32 device to Google Home app using a Nest Hub, so I tried to share the device from there to Home Assistant, but it didn't work neither.
I'm also able to commissioning the device to [GHSAFM](https://github.com/google-home/sample-app-for-matter-android), so I tried to share from there to Home Assistant also, but no luck...

<details>
  <summary>Home Assistant Logs</summary>

  ```
  2023-04-05 19:31:17 core-matter-server chip.CTL[127] INFO Discovered device to be commissioned over DNS-SD
  2023-04-05 19:31:17 core-matter-server chip.CTL[127] INFO Discovered device to be commissioned over DNS-SD
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36560i M:50121676 (Ack:190294838)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:40 (SecureChannel:StatusReport)
  2023-04-05 19:31:18 core-matter-server chip.SC[127] INFO SecureSession[0x7f84037680]: Moving from state 'kEstablishing' --> 'kActive'
  2023-04-05 19:31:18 core-matter-server chip.BLE[127] ERROR BleConnectionDelegate::CancelConnection is not implemented.
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'SecurePairing' -> 'ReadCommissioningInfo'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'ReadCommissioningInfo'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Sending request for commissioning information
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36561i M:102878458] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878458 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36560i M:190294839 (Ack:50121676)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (U) Sending msg 190294839 to IP address 'UDP:[fe80::1252:1cff:fe62:b430%eth0]:5540'
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36561i M:120323926 (Ack:102878458)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:05 (IM:ReportData)
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO ----- NetworkCommissioning Features: has WiFi. endpointid = 0
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'ReadCommissioningInfo'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'ReadCommissioningInfo' -> 'ArmFailSafe'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'ArmFailSafe'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Arming failsafe (60 seconds)
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36562i M:102878459] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878459 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36561i M:102878460 (Ack:120323926)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878460 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36562i M:120323927 (Ack:102878459)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
  2023-04-05 19:31:18 core-matter-server chip.DMG[127] INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Received ArmFailSafe response errorCode=0
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'ArmFailSafe'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'ArmFailSafe' -> 'ConfigRegulatory'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'ConfigRegulatory'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Setting Regulatory Config
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Device does not support configurable regulatory location
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36563i M:102878461] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878461 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36562i M:102878462 (Ack:120323927)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878462 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36563i M:120323928 (Ack:102878461)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
  2023-04-05 19:31:18 core-matter-server chip.DMG[127] INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0003
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Received SetRegulatoryConfig response errorCode=0
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'ConfigRegulatory'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'ConfigRegulatory' -> 'SendPAICertificateRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'SendPAICertificateRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Sending request for PAI certificate
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36564i M:102878463] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878463 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36563i M:102878464 (Ack:120323928)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878464 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36564i M:120323929 (Ack:102878463)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
  2023-04-05 19:31:18 core-matter-server chip.DMG[127] INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_003E Command=0x0000_0003
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Received certificate chain from the device
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'SendPAICertificateRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'SendPAICertificateRequest' -> 'SendDACCertificateRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'SendDACCertificateRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Sending request for DAC certificate
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36565i M:102878465] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878465 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36564i M:102878466 (Ack:120323929)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878466 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36565i M:120323930 (Ack:102878465)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
  2023-04-05 19:31:18 core-matter-server chip.DMG[127] INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_003E Command=0x0000_0003
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Received certificate chain from the device
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'SendDACCertificateRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'SendDACCertificateRequest' -> 'SendAttestationRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'SendAttestationRequest'
  2023-04-05 19:31:18 core-matter-server chip.CTL[127] INFO Sending Attestation Request to the device.
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36566i M:102878467] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878467 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO <<< [E:36565i M:102878468 (Ack:120323930)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:18 core-matter-server chip.IN[127] INFO (S) Sending msg 102878468 on secure session with LSID: 9861
  2023-04-05 19:31:18 core-matter-server chip.EM[127] INFO >>> [E:36566i M:120323931 (Ack:102878467)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:19 core-matter-server chip.EM[127] INFO >>> [E:36566i M:120323932 (Ack:102878467)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
  2023-04-05 19:31:19 core-matter-server chip.DMG[127] INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_003E Command=0x0000_0001
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Received Attestation Information from the device
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'SendAttestationRequest'
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Commissioning stage next step: 'SendAttestationRequest' -> 'AttestationVerification'
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'AttestationVerification'
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Verifying attestation
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] ERROR Failed in verifying 'Attestation Information' command received from the device: err 101. Look at AttestationVerificationResult enum to understand the errors
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Error on commissioning step 'AttestationVerification': '../src/controller/CHIPDeviceController.cpp:1075: CHIP Error 0x000000AC: Internal error'
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] ERROR Failed to perform commissioning step 8
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Going from commissioning step 'AttestationVerification' with lastErr = '../src/controller/CHIPDeviceController.cpp:1075: CHIP Error 0x000000AC: Internal error' -> 'Cleanup'
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Performing next commissioning step 'Cleanup' with completion status = '../src/controller/CHIPDeviceController.cpp:1075: CHIP Error 0x000000AC: Internal error'
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Expiring failsafe on proxy 0x7f8404f5f0
  2023-04-05 19:31:19 core-matter-server chip.EM[127] INFO <<< [E:36567i M:102878469] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
  2023-04-05 19:31:19 core-matter-server chip.IN[127] INFO (S) Sending msg 102878469 on secure session with LSID: 9861
  2023-04-05 19:31:19 core-matter-server chip.EM[127] INFO <<< [E:36566i M:102878470 (Ack:120323932)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
  2023-04-05 19:31:19 core-matter-server chip.IN[127] INFO (S) Sending msg 102878470 on secure session with LSID: 9861
  2023-04-05 19:31:19 core-matter-server chip.EM[127] INFO >>> [E:36567i M:120323933 (Ack:102878469)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
  2023-04-05 19:31:19 core-matter-server chip.DMG[127] INFO Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Failsafe disarmed
  2023-04-05 19:31:19 core-matter-server chip.CTL[127] INFO Successfully finished commissioning step 'Cleanup'
  2023-04-05 19:31:19 core-matter-server chip.SC[127] INFO SecureSession[0x7f84037680]: Moving from state 'kActive' --> 'kPendingEviction'
  2023-04-05 19:31:19 core-matter-server matter_server.server.client_handler[127] ERROR [547950689968] Error handling message: CommandMessage(message_id='a775bfd4d7934b259c7a4152e8d72151', command='commission_with_code', args={'code': '00030406855'})
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
      result = await result
    File "/usr/local/lib/python3.10/site-packages/matter_server/server/device_controller.py", line 152, in commission_with_code
      raise NodeCommissionFailed(
  matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 5
  2023-04-05 19:31:19 core-matter-server chip.EM[127] ERROR Failed to send Solitary ack for MessageCounter:120323933 on exchange 36567i:../src/messaging/ExchangeContext.cpp:144: CHIP Error 0x00000002: Connection aborted
  2023-04-05 19:31:26 core-matter-server chip.CTL[127] ERROR Commissioning discovery over BLE failed: ../src/platform/Linux/BLEManagerImpl.cpp:814: CHIP Error 0x00000032: Timeout
  2023-04-05 19:31:26 core-matter-server chip.-[127] ERROR ../src/platform/Linux/BLEManagerImpl.cpp:814: CHIP Error 0x00000032: Timeout at ../src/controller/SetUpCodePairer.cpp:299
  ```

</details>

**Comment by marcelveldt** [comment]
Are you running the matter add-on as provided (and supported) by us ?
If you are running the matter server in some other way, you will have some issues with paths, especially for certificates.

**Comment by ArturoGuerra** [comment]
Are you by any chance running the matter server in docker?

**Comment by Diegorro98** [comment]
@marcelveldt I'm running the Matter Addon provided by you yes.

@ArturoGuerra currently I'm running Home Assistant OS in a Raspberry Pi 3B+, but this also happened to me using Home Assistant OS at Hyper-V (with bridged network so that Home Assistant is exposed to the local network to avoid mDNS problems)

**Comment by marcelveldt** [comment]
ah thanks, that rules out the certificates path. I'm afraid the attestation certificate of this device is missing then, maybe because you pulled the latest (which is probably pointed at a newer sdk source). Can you check with the sample apps hosted by us ?

https://nabucasa.github.io/matter-example-apps

That commissioning to other apps does work with the incorrect certificate is because they allow you to bypass attestation (its that prompt if you trust the device) while we do require attestation

**Comment by ArturoGuerra** [comment]
It appears its cuz we are missing the first 4 certs here, those seem to be specifically for the test VID's and apparently those are not downloaded through their provided script https://github.com/project-chip/connectedhomeip/tree/master/credentials/development/paa-root-certs

**Comment by marcelveldt** [comment]
Yeah, I was suspecting that, hence the question above to test with our precompiled example apps which include a certificate from the DCA. Maybe we should include them by default if they don't change that often

**Comment by ArturoGuerra** [comment]
Yeah, those haven't changed in over a year so it should be safe to just add them.

**Comment by Diegorro98** [comment]
> Can you check with the sample apps hosted by us ?
>
> https://nabucasa.github.io/matter-example-apps
@marcelveldt  I tried, but doesn't allow me to install it because it seems that my esp32 board is not supported (Which seems reasonable because I'm trying to install an app for ESP32-C3-DevKitM-1, and I have an ESP32-DevKitC)

Then should I do something to fix this problem or should I wait for any change that you might do?
