### ISSUE TITLE
matter_server.common.errors.NodeInterviewFailed: Failed to interview node 1

### ISSUE THREAD

**Issue by codyc1515** [home-assistant-libs/python-matter-server#278]
I am using a Philips hue bridge with several lights and a plug. This was working okay until I restarted the system. I am using Docker. Now, I am receiving the following error every time:

```
Starting server: matter-server --storage-path /data
2023-04-21 01:19:28 kopiko4 matter_server.server.stack[1] INFO Initializing CHIP/Matter Controller Stack...
[1682039968.839370][1:1] CHIP:CTL: Setting attestation nonce to random value
[1682039968.839843][1:1] CHIP:CTL: Setting CSR nonce to random value
[1682039968.841782][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1682039968.845162][1:1] CHIP:DL: writing settings to file (/tmp/chip_kvs-LMXLih)
[1682039968.845569][1:1] CHIP:DL: renamed tmp file to file (/tmp/chip_kvs)
[1682039968.845966][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1682039968.846795][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_config.ini
[1682039968.847475][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_counters.ini
[1682039968.848057][1:1] CHIP:DL: writing settings to file (/data/chip_counters.ini-3OTYJi)
[1682039968.849278][1:1] CHIP:DL: renamed tmp file to file (/data/chip_counters.ini)
[1682039968.849659][1:1] CHIP:DL: NVS set: chip-counters/reboot-count = 30 (0x1E)
[1682039968.850633][1:1] CHIP:DL: Got Ethernet interface: eth0
[1682039968.851398][1:1] CHIP:DL: Found the primary Ethernet interface:eth0
[1682039968.852212][1:1] CHIP:DL: Got WiFi interface: wlan0
[1682039968.852427][1:1] CHIP:DL: Failed to reset WiFi statistic counts
2023-04-21 01:19:28 kopiko4 PersistentStorage[1] WARNING Initializing persistent storage from file: /data/chip.json
2023-04-21 01:19:28 kopiko4 PersistentStorage[1] WARNING Loading configuration from /data/chip.json...
2023-04-21 01:19:28 kopiko4 chip.TS[1] INFO Last Known Good Time: 2023-04-18T07:58:04
2023-04-21 01:19:28 kopiko4 chip.FP[1] INFO Fabric index 0x1 was retrieved from storage. Compressed FabricId 0x66F7685D0094D365, FabricId 0x0000000000000001, NodeId 0x000000000001B669, VendorId 0xFFF1
2023-04-21 01:19:28 kopiko4 PersistentStorage[1] INFO SetSdkKey: g/gcc = b'0u\x00\x00'
2023-04-21 01:19:28 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:28 kopiko4 PersistentStorage[1] INFO SetSdkKey: g/gdc = b'0u\x00\x00'
2023-04-21 01:19:28 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:28 kopiko4 chip.ZCL[1] INFO Using ZAP configuration...
2023-04-21 01:19:28 kopiko4 chip.DL[1] ERROR MDNS failed to join multicast group on wlan0 for address type IPv4: ../src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-04-21 01:19:28 kopiko4 chip.DL[1] ERROR MDNS failed to join multicast group on veth541f523 for address type IPv4: ../src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-04-21 01:19:28 kopiko4 chip.DL[1] ERROR MDNS failed to join multicast group on vethfc9b850 for address type IPv4: ../src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-04-21 01:19:29 kopiko4 CertificateAuthorityManager[1] WARNING Loading certificate authorities from storage...
2023-04-21 01:19:29 kopiko4 CertificateAuthority[1] WARNING New CertificateAuthority at index 1
2023-04-21 01:19:29 kopiko4 CertificateAuthority[1] WARNING Loading fabric admins from storage...
2023-04-21 01:19:29 kopiko4 FabricAdmin[1] WARNING New FabricAdmin: FabricId: 0x0000000000000001, VendorId = 0xFFF1
2023-04-21 01:19:29 kopiko4 PersistentStorage[1] INFO SetReplKey: caList = {'1': [{'fabricId': 1, 'vendorId': 65521}]}
2023-04-21 01:19:29 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:29 kopiko4 matter_server.server.stack[1] INFO CHIP Controller Stack initialized.
2023-04-21 01:19:29 kopiko4 matter_server.server.server[1] INFO Starting the Matter Server...
2023-04-21 01:19:29 kopiko4 matter_server.server.helpers.paa_certificates[1] INFO Fetching the latest PAA root certificates from DCL.
2023-04-21 01:19:50 kopiko4 matter_server.server.helpers.paa_certificates[1] INFO Fetched 78 PAA root certificates from DCL.
2023-04-21 01:19:50 kopiko4 matter_server.server.helpers.paa_certificates[1] INFO Fetching the latest PAA root certificates from Git.
2023-04-21 01:19:52 kopiko4 matter_server.server.helpers.paa_certificates[1] INFO Fetched 2 PAA root certificates from Git.
2023-04-21 01:19:52 kopiko4 FabricAdmin[1] WARNING Allocating new controller with CaIndex: 1, FabricId: 0x0000000000000001, NodeId: 0x000000000001B669, CatTags: []
2023-04-21 01:19:52 kopiko4 chip.CTL[1] INFO Setting attestation nonce to random value
2023-04-21 01:19:52 kopiko4 chip.CTL[1] INFO Setting CSR nonce to random value
2023-04-21 01:19:52 kopiko4 chip.SPT[1] INFO Using device attestation PAA trust store path /usr/local/lib/python3.10/site-packages/credentials/development/paa-root-certs.
2023-04-21 01:19:53 kopiko4 chip.CTL[1] INFO Generating NOC
2023-04-21 01:19:53 kopiko4 chip.FP[1] INFO Validating NOC chain
2023-04-21 01:19:53 kopiko4 chip.FP[1] INFO NOC chain validation successful
2023-04-21 01:19:53 kopiko4 chip.FP[1] INFO Updated fabric at index: 0x1, Node ID: 0x000000000001B669
2023-04-21 01:19:53 kopiko4 chip.TS[1] INFO Last Known Good Time: 2023-04-18T07:58:04
2023-04-21 01:19:53 kopiko4 chip.TS[1] INFO New proposed Last Known Good Time: 2021-01-01T00:00:00
2023-04-21 01:19:53 kopiko4 chip.TS[1] INFO Retaining current Last Known Good Time
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO SetSdkKey: g/fs/c = b'\x15$\x00\x01(\x01\x18'
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO SetSdkKey: f/1/m = b'\x15%\x00\xf1\xff,\x01\x00\x18'
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 chip.FP[1] INFO Metadata for Fabric 0x1 persisted to storage.
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO SetSdkKey: f/1/n = xxxxxxxxxxxxxxx
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO SetSdkKey: f/1/i = xxxxxxxxxxxxxxx
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 chip.TS[1] INFO Committing Last Known Good Time to storage: 2023-04-18T07:58:04
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO SetSdkKey: g/lkgt = b'\x15&\x00\x0c\n\xd1+\x18'
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO DeleteSdkKey: g/fs/c
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 chip.CTL[1] INFO Joined the fabric at index 1. Fabric ID is 0x0000000000000001 (Compressed Fabric ID: 66F7685D0094D365)
2023-04-21 01:19:53 kopiko4 chip.CTL[1] INFO *** Missing DeviceAttestationVerifier configuration at DeviceCommissioner init: using global default, consider passing one in CommissionerInitParams.
2023-04-21 01:19:53 kopiko4 chip.SPT[1] INFO Setting up group data for Fabric Index 1 with Compressed Fabric ID:
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO SetSdkKey: f/1/k/0 = xxxxxxxxxxxxxxx
2023-04-21 01:19:53 kopiko4 PersistentStorage[1] INFO Committing...
2023-04-21 01:19:53 kopiko4 matter_server.server.vendor_info[1] INFO Loading vendor info from storage.
2023-04-21 01:19:53 kopiko4 matter_server.server.vendor_info[1] INFO Loaded 57 vendors from storage.
2023-04-21 01:19:53 kopiko4 matter_server.server.vendor_info[1] INFO Fetching the latest vendor info from DCL.
2023-04-21 01:19:53 kopiko4 chip.DIS[1] INFO Checking node lookup status after 201 ms
2023-04-21 01:19:53 kopiko4 matter_server.server.vendor_info[1] INFO Fetched 57 vendors from DCL.
2023-04-21 01:19:53 kopiko4 matter_server.server.vendor_info[1] INFO Saving vendor info to storage.
2023-04-21 01:20:24 kopiko4 chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-04-21 01:20:38 kopiko4 chip.DIS[1] INFO Checking node lookup status after 45000 ms
2023-04-21 01:20:38 kopiko4 chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: ../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:96: CHIP Error 0x00000032: Timeout
2023-04-21 01:20:38 kopiko4 matter_server.server.device_controller[1] WARNING Unable to interview Node 1, we will retry later in the background.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/matter_server/server/device_controller.py", line 288, in interview_node
    await self._call_sdk(self.chip_controller.ResolveNode, nodeid=node_id)
  File "/usr/local/lib/python3.10/site-packages/matter_server/server/device_controller.py", line 524, in _call_sdk
    await self.server.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 588, in ResolveNode
    self.GetConnectedDeviceSync(nodeid, allowPASE=False)
  File "/usr/local/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 827, in GetConnectedDeviceSync
    returnErr.raise_on_error()
  File "/usr/local/lib/python3.10/site-packages/chip/native/__init__.py", line 66, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: ../src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:96: CHIP Error 0x00000032: Timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/matter_server/server/device_controller.py", line 549, in _interview_node
    await self.interview_node(node_id)
  File "/usr/local/lib/python3.10/site-packages/matter_server/server/device_controller.py", line 295, in interview_node
    raise NodeInterviewFailed(f"Failed to interview node {node_id}") from err
matter_server.common.errors.NodeInterviewFailed: Failed to interview node 1
```

**Comment by ArturoGuerra** [comment]
Hue released a firmware update yesterday that reset all the matter fabrics as they switched from the development to production certificate so you'll have to delete the bridge and pair it again

**Comment by codyc1515** [comment]
Fantastic! Thank you for letting me know. I'll give it a try.

**Comment by codyc1515** [comment]
Hey. Sorry I didn’t let you know. I tried repairing but was still facing issues. Obliterated my `data` folder and was able to re-pair. All working again now. Thanks again.
