### ISSUE TITLE
Pairing fails with nRF5340 DK running Matter Window covering sample

### ISSUE THREAD

**Issue by lboue** [home-assistant-libs/python-matter-server#311]
Hello,

I trying to pair a Nordic Semiconductor [NRF5340-DK](https://www.nordicsemi.com/Products/Development-hardware/nRF5340-DK) with my home-assistant Matter server.
I build and flash this development kit with the [window covering sample](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/matter/window_covering/README.html). 

_This sample demonstrates the usage of the Matter application layer to build a window covering device. This device works as a Matter accessory device, meaning it can be paired and controlled remotely over a Matter network built on top of a low-power 802.15.4 Thread network._

_The sample uses buttons for gradually changing the position and movement mode of the window cover, and LEDs to show the state of these changes. The following movement modes are available:
  Lift - In this movement mode, the window cover moves up and down.
  Tilt - In this movement mode, the window cover slats are tilted forward or backward without the cover moving vertically._

### Error
I noticed this error in the core-matter-server log:
```
2023-06-01 14:50:24 core-matter-server matter_server.server.device_controller.8[125] DEBUG Attribute updated: TypedAttributePath(ClusterType=<class 'chip.clusters.Objects.OccupancySensing'>, AttributeType=<class 'chip.clusters.Objects.OccupancySensing.Attributes.Occupancy'>, AttributeName='occupancy', Path=AttributePath(EndpointId=1, ClusterId=1030, AttributeId=0)) - new value: 0
2023-06-01 14:50:24 core-matter-server chip.clusters.Attribute[125] ERROR 'No Schema found for Attribute 1/319486977/319422471'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/Attribute.py", line 754, in _handleReportEnd
    attribute_path = TypedAttributePath(Path=change)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/Attribute.py", line 149, in __init__
    raise KeyError(f"No Schema found for Attribute {Path}")
KeyError: 'No Schema found for Attribute 1/319486977/319422471'
2023-06-01 14:50:24 core-matter-server chip.DMG[125] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xb2b0fa2c Peer = 01:0000000000000008
2023-06-01 14:50:24 core-matter-server chip.EM[125] INFO <<< [E:63676r S:18859 M:177814659 (Ack:38766941)] (S) Msg TX to 1:0000000000000008 [B54E] --- Type 0001:01 (IM:StatusResponse)
2023-06-01 14:50:24 core-matter-server chip.IN[125] INFO (S) Sending msg 177814659 on secure session with LSID: 18859
2023-06-01 14:50:24 core-matter-server chip.EM[125] INFO >>> [E:63676r S:18859 M:38766942 (Ack:177814659)] (S) Msg RX from 1:0000000000000008 [B54E] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-01 14:50:24 core-matter-server chip.EM[125] DEBUG Found matching exchange: 63676r, Delegate: (nil)
2023-06-01 14:50:24 core-matter-server chip.EM[125] DEBUG Rxd Ack; Removing MessageCounter:177814659 from Retrans Table on exchange 63676r
2023-06-01 14:50:32 core-matter-server chip.EM[125] INFO >>> [E:19037r S:18864 M:30421151] (S) Msg RX from 1:0000000000000011 [B54E] --- Type 0001:05 (IM:ReportData)
2023-06-01 14:50:32 core-matter-server chip.EM[125] DEBUG Handling via exchange: 19037r, Delegate: 0xffffb3789c90
2023-06-01 14:50:32 core-matter-server chip.DMG[125] DEBUG ReportDataMessage =
2023-06-01 14:50:32 core-matter-server chip.DMG[125] DEBUG {
2023-06-01 14:50:32 core-matter-server chip.DMG[125] DEBUG 	SubscriptionId = 0x4858000d,
2023-06-01 14:50:32 core-matter-server chip.DMG[125] DEBUG 	InteractionModelRevision = 1
2023-06-01 14:50:32 core-matter-server chip.DMG[125] DEBUG }
2023-06-01 14:50:32 core-matter-server chip.DMG[125] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x4858000d Peer = 01:0000000000000011
2023-06-01 14:50:32 core-matter-server chip.EM[125] INFO <<< [E:19037r S:18864 M:184085434 (Ack:30421151)] (S) Msg TX to 1:0000000000000011 [B54E] --- Type 0001:01 (IM:StatusResponse)
2023-06-01 14:50:32 core-matter-server chip.IN[125] INFO (S) Sending msg 184085434 on secure session with LSID: 18864
2023-06-01 14:50:32 core-matter-server chip.EM[125] INFO >>> [E:19037r S:18864 M:30421152 (Ack:184085434)] (S) Msg RX from 1:0000000000000011 [B54E] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-01 14:50:32 core-matter-server chip.EM[125] DEBUG Found matching exchange: 19037r, Delegate: (nil)
2023-06-01 14:50:32 core-matter-server chip.EM[125] DEBUG Rxd Ack; Removing MessageCounter:184085434 from Retrans Table on exchange 19037r
2023-06-01 14:50:43 core-matter-server matter_server.server.storage[125] DEBUG Saved data to persistent storage
```

Would you be able to tell me how to download the complete log file to try to solve this problem?
I only have a partial debug file: [HA-core-matter-server.log](https://github.com/home-assistant-libs/python-matter-server/files/11625596/HA-core-matter-server.log)

Here is the full log from nRF DK: [nRF5340-window-cover-matter.log](https://github.com/home-assistant-libs/python-matter-server/files/11625544/nRF5340-window-cover-matter.log)

### Env
**Home Assistant**
- Home Assistant 2023.6.0b1
- Supervisor 2023.05.0
- Operating System 10.2
- Frontend 20230601.0
- Matter Server: 4.5.1
- OpenThread Border Router: 2.0.0

**Nordic**
- nRF SDK 2.4.0

Regards

**Comment by marcelveldt** [comment]
You can ignore the error you posted above, that is simple enough just an unparseable value, most probably vendor specific.

If you got to this point pairing already succeeded so what is the issue ?
Or do you have other devices already paired and is the log just completely irrelevant ?

To get the full log: Within Home Assistant settings go to System --> Logs --> Select the Matter add-on in the top right.

**Comment by lboue** [comment]
I did the test. Pairing it to Apple Home is OK as you can see:
![IMG_3014_](https://github.com/home-assistant-libs/python-matter-server/assets/938089/8a434b60-48af-4957-b89f-a06f70eecd00)

But share from Apple Home to HA fails:
![IMG_3013__](https://github.com/home-assistant-libs/python-matter-server/assets/938089/73abd914-be31-4320-a3b4-48824cbc31a9)

**Comment by lboue** [comment]
Here is log HA log file:
[HA-matter-failure.log](https://github.com/home-assistant-libs/python-matter-server/files/11639543/HA-matter-failure.log)

**Comment by marcelveldt** [comment]
Hmm, that log is not very useful as it only contains a very small portion of the full log mostly due to the loglevel being set to debug. Can you try to grab the full log after commissioning ?

To grab the full log: Install the SSH (or terminal) Add-on in HA. Use the SSH add-on execute this comand:
`ha host logs --identifier addon_core_matter_server`

Is the HA host on the exact same network/subnet as your iOS device(s) ?
And you are running Home Assistant OS on dedicated hardware, not virtualized ?

**Comment by lboue** [comment]
Home Assistant OS is running on a VM (haos_ova-10.2.qcow)
I did a test this morning. Pairing succeed but iOS app is stucked at "Add Matter device" step: 

```
File "/usr/local/lib/python3.11/site-packages/chip/clusters/Attribute.py", line 149, in __init__
    raise KeyError(f"No Schema found for Attribute {Path}")
KeyError: 'No Schema found for Attribute 1/319486977/319422471'
```

**Frontend**
![image](https://github.com/home-assistant-libs/python-matter-server/assets/938089/54e68792-a80c-4900-9aba-4c35dfc11b1f)


```
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 	
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 	EventReportIBs =
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 	[
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 		EventReportIB =
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 		{
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 			EventDataIB =
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 			{
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				EventPath =
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				{
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					Endpoint = 0x0,
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					Cluster = 0x2a,
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					Event = 0x0,
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				},
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				EventNumber = 0xd,
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				PriorityLevel = 0x1,
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				SystemTimestamp = 0x7b343,
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				EventData = 
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				{
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					0x0 = 2, 
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					0x1 = 3, 
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					0x2 = 4, 
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 					0x3 = NULL
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 				},
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 			},
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 			
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 		},
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 		
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 	],
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 	
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG 	InteractionModelRevision = 1
2023-06-05 11:11:47 core-matter-server chip.DMG[126] DEBUG }
2023-06-05 11:11:47 core-matter-server matter_server.server.device_controller.24[126] DEBUG Received node event: EventReadResult(Header=EventHeader(EndpointId=0, ClusterId=42, EventId=0, EventNumber=13, Priority=<EventPriority.DEBUG: 1>, Timestamp=504643, TimestampType=<EventTimestampType.SYSTEM: 0>), Status=<Status.Success: 0>, Data=OtaSoftwareUpdateRequestor.Events.StateTransition(previousState=<OTAUpdateStateEnum.kQuerying: 2>, newState=<OTAUpdateStateEnum.kDelayedOnQuery: 3>, reason=<OTAChangeReasonEnum.kDelayByProvider: 4>, targetSoftwareVersion=Null))
2023-06-05 11:11:47 core-matter-server matter_server.server.device_controller.24[126] DEBUG Attribute updated: TypedAttributePath(ClusterType=<class 'chip.clusters.Objects.OtaSoftwareUpdateRequestor'>, AttributeType=<class 'chip.clusters.Objects.OtaSoftwareUpdateRequestor.Attributes.UpdateState'>, AttributeName='updateState', Path=AttributePath(EndpointId=0, ClusterId=42, AttributeId=2)) - new value: 3
2023-06-05 11:11:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xfa625246 Peer = 01:0000000000000018
2023-06-05 11:11:47 core-matter-server chip.EM[126] INFO <<< [E:43967r S:49353 M:211498408 (Ack:138311924)] (S) Msg TX to 1:0000000000000018 [B54E] --- Type 0001:01 (IM:StatusResponse)
2023-06-05 11:11:47 core-matter-server chip.IN[126] INFO (S) Sending msg 211498408 on secure session with LSID: 49353
2023-06-05 11:11:47 core-matter-server chip.EM[126] INFO >>> [E:43967r S:49353 M:138311925 (Ack:211498408)] (S) Msg RX from 1:0000000000000018 [B54E] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-05 11:11:47 core-matter-server chip.EM[126] DEBUG Found matching exchange: 43967r, Delegate: (nil)
2023-06-05 11:11:47 core-matter-server chip.EM[126] DEBUG Rxd Ack; Removing MessageCounter:211498408 from Retrans Table on exchange 43967r
2023-06-05 11:11:49 core-matter-server chip.EM[126] INFO >>> [E:18585r S:49327 M:258516769] (S) Msg RX from 1:0000000000000008 [B54E] --- Type 0001:05 (IM:ReportData)
2023-06-05 11:11:49 core-matter-server chip.EM[126] DEBUG Handling via exchange: 18585r, Delegate: 0xffff8334fc90
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG ReportDataMessage =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG {
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 	SubscriptionId = 0xc16ad0a8,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 	AttributeReportIBs =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 	[
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		AttributeReportIB =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		{
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			AttributeDataIB =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			{
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				DataVersion = 0x987fe458,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				AttributePathIB =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				{
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					Endpoint = 0x1,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					Cluster = 0x406,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					Attribute = 0x0000_0000,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				}
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				Data = 1, 
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			},
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		},
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		AttributeReportIB =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		{
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			AttributeDataIB =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			{
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				DataVersion = 0x1a03a4b,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				AttributePathIB =
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				{
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					Endpoint = 0x1,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					Cluster = 0x130afc01,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					Attribute = 0x130A_0007,
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				}
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 					
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 				Data = 5761411, 
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			},
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 			
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		},
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 		
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 	],
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 	
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG 	InteractionModelRevision = 1
2023-06-05 11:11:49 core-matter-server chip.DMG[126] DEBUG }
2023-06-05 11:11:49 core-matter-server chip.clusters.Attribute[126] ERROR 'No Schema found for Attribute 1/319486977/319422471'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/Attribute.py", line 754, in _handleReportEnd
    attribute_path = TypedAttributePath(Path=change)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/Attribute.py", line 149, in __init__
    raise KeyError(f"No Schema found for Attribute {Path}")
KeyError: 'No Schema found for Attribute 1/319486977/319422471'
2023-06-05 11:11:49 core-matter-server matter_server.server.device_controller.8[126] DEBUG Attribute updated: TypedAttributePath(ClusterType=<class 'chip.clusters.Objects.OccupancySensing'>, AttributeType=<class 'chip.clusters.Objects.OccupancySensing.Attributes.Occupancy'>, AttributeName='occupancy', Path=AttributePath(EndpointId=1, ClusterId=1030, AttributeId=0)) - new value: 1
2023-06-05 11:11:49 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xc16ad0a8 Peer = 01:0000000000000008
2023-06-05 11:11:49 core-matter-server chip.EM[126] INFO <<< [E:18585r S:49327 M:169619539 (Ack:258516769)] (S) Msg TX to 1:0000000000000008 [B54E] --- Type 0001:01 (IM:StatusResponse)
2023-06-05 11:11:49 core-matter-server chip.IN[126] INFO (S) Sending msg 169619539 on secure session with LSID: 49327
2023-06-05 11:11:49 core-matter-server chip.EM[126] INFO >>> [E:18585r S:49327 M:258516770 (Ack:169619539)] (S) Msg RX from 1:0000000000000008 [B54E] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-05 11:11:49 core-matter-server chip.EM[126] DEBUG Found matching exchange: 18585r, Delegate: (nil)
2023-06-05 11:11:49 core-matter-server chip.EM[126] DEBUG Rxd Ack; Removing MessageCounter:169619539 from Retrans Table on exchange 18585r
```

**Comment by lboue** [comment]
> Hmm, that log is not very useful as it only contains a very small portion of the full log mostly due to the loglevel being set to debug. Can you try to grab the full log after commissioning ?
> 
> To grab the full log: Install the SSH (or terminal) Add-on in HA. Use the SSH add-on execute this comand: `ha host logs --identifier addon_core_matter_server`

How can I grab the file after issuing this command?

**Comment by marcelveldt** [comment]
Ah, we have seen other reports of non working comisioning when using a virtualized environment. One other user reported that enabling "promiscuous mode" on the network adapter fixed it so that's worth a shot.

Once you issue that command, the log should be printed on the console, did it not ?

**Comment by marcelveldt** [comment]
Do I read correctly that the iOS app is still stuck at "Add Matter device" but the device actually showed up within HA ? Or did I read it wrong ?

**Comment by lboue** [comment]
> Do I read correctly that the iOS app is still stuck at "Add Matter device" but the device actually showed up within HA ? Or did I read it wrong ?

Yes today pairing succeed
