### ISSUE TITLE
 OSError: libnl-route-3.so.200: cannot open shared object file

### ISSUE THREAD

**Issue by ljmerza** [home-assistant-libs/python-matter-server#313]
matter server stopped working a few days ago and i get this error

```
2023-06-04T15:23:31.559046335Z OSError: libnl-route-3.so.200: cannot open shared object file: No such file or directory
2023-06-04T15:23:45.779802592Z Starting server: matter-server --storage-path /data
2023-06-04T15:23:52.595876267Z 2023-06-04 11:23:52 z3 matter_server.server.stack[1] INFO Initializing CHIP/Matter Controller Stack...
2023-06-04T15:23:52.600023054Z Traceback (most recent call last):
2023-06-04T15:23:52.600141386Z   File "/usr/local/bin/matter-server", line 8, in <module>
2023-06-04T15:23:52.601046378Z     sys.exit(main())
2023-06-04T15:23:52.601141013Z              ^^^^^^
2023-06-04T15:23:52.601167784Z   File "/usr/local/lib/python3.11/site-packages/matter_server/server/__main__.py", line 79, in main
2023-06-04T15:23:52.601671425Z     server = MatterServer(
2023-06-04T15:23:52.601742883Z              ^^^^^^^^^^^^^
2023-06-04T15:23:52.602102932Z   File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 74, in __init__
2023-06-04T15:23:52.602721833Z     self.stack = MatterStack(self)
2023-06-04T15:23:52.603168496Z                  ^^^^^^^^^^^^^^^^^
2023-06-04T15:23:52.603263130Z   File "/usr/local/lib/python3.11/site-packages/matter_server/server/stack.py", line 29, in __init__
2023-06-04T15:23:52.603807084Z     chip.native.Init()
2023-06-04T15:23:52.604211351Z   File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 194, in Init
2023-06-04T15:23:52.604905043Z     _GetLibraryHandle(False).pychip_CommonStackInit(ctypes.c_char_p(params))
2023-06-04T15:23:52.605326446Z     ^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-04T15:23:52.605393268Z   File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 178, in _GetLibraryHandle
2023-06-04T15:23:52.606240865Z     _nativeLibraryHandle = ctypes.CDLL(FindNativeLibraryPath())
2023-06-04T15:23:52.606776485Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-04T15:23:52.606848568Z   File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
2023-06-04T15:23:52.607726477Z     self._handle = _dlopen(self._name, mode)
2023-06-04T15:23:52.608244025Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

running raspbeery pi 3 docker

```
 matter:
    platform: linux/arm64/v8
    build:
      context: ./python-matter-server
      dockerfile: Dockerfile.dev
    # image: matter-server:latest
    container_name: matter
    restart: unless-stopped
    env_file: ./global.env
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./volumes/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
```

verified folder permissions are fine

**Comment by marcelveldt** [comment]
https://github.com/home-assistant-libs/python-matter-server/issues/308

That said, I really don't believe a pi3 is supported, let alone powerful enough.

**Comment by wasnertobias** [comment]
Thanks for your reply on this closed issue. I understand that this is not officially supported and have not expected any answer.

However to my understanding the new dependencies should just be installed in the Docker container as they have been added in the Dockerfile correspondingly - as far as I can see. So I am confused and don't see how missing dependencies should be the issue in this case.

Just to clarify: We are trying to run the docker container with the provided compose.yml - this used to work like a charm.

**Comment by ljmerza** [comment]
looks like the dockerfile wasnt ekpt up to date as its for development use only. youll need to add 

```
       libnl-3-200 \
       libnl-route-3-200 \
```

to your `dockerfile.dev` file to get it working again at least until the official dockerfile comes out for public use.
