### ISSUE TITLE
Errors when Pairing Nanoleaf Essentials Lightstrip with Home Assistant over Matter/Thread

### ISSUE THREAD

**Issue by trrevvorr** [home-assistant-libs/python-matter-server#319]
I have three Nanoleaf Essentials lightstrips (matter version) and I've been able to pair two out of the three, the third device is where I'm seeing errors. These devices work over thread but don't have SkyConnect - but I do have a few Apple HomePods. To add the lightstrips to Home Assistant, I do the following:
1. Commission device via Nanoleaf app
2. Opt to add device to Apple home via Nanoleaf app
3. From Apple Home app, navigate to device, click "Turn On Pairing Mode" > "Copy Code"
4. In Home Assistant iOS app, click "Add Device" > "Add Matter Device"
5. The "Add Accessory" dialog pops up, I click "More options..." > The device I'm setting up > paste the code from before
6. After waiting around a minute, I get an "Unable to Pair" error

I believe this is an issue with Home Assistant because, using this same process, I paired the device with Google Home without issue. So far Home Assistant is the only platform that this device could not pair with. Additionally, the other two Nanoleaf lightstrips paired with HA just fine (might have had to retry once or twice). 

Here's the versions:
- Home Assistant 2023.6.1
- Supervisor 2023.06.1
- Operating System 10.2
- Frontend 20230608.0
- Matter Server 4.6.0

Here's the output from the Matter Server Logs:
```
2023-06-11 08:20:16 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from Git.
2023-06-11 08:20:16 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 0 PAA root certificates from Git.
2023-06-11 08:20:16 core-matter-server chip.CTL[126] INFO Setting attestation nonce to random value
2023-06-11 08:20:16 core-matter-server chip.CTL[126] INFO Setting CSR nonce to random value
2023-06-11 08:20:16 core-matter-server chip.CTL[126] INFO Starting commissioning discovery over BLE
2023-06-11 08:20:16 core-matter-server chip.CTL[126] INFO Starting commissioning discovery over DNS-SD
2023-06-11 08:20:16 core-matter-server chip.CTL[126] ERROR Commissioning discovery over BLE failed: src/platform/Linux/BLEManagerImpl.cpp:682: CHIP Error 0x00000003: Incorrect state
2023-06-11 08:20:16 core-matter-server chip.-[126] ERROR src/platform/Linux/BLEManagerImpl.cpp:682: CHIP Error 0x00000003: Incorrect state at src/controller/SetUpCodePairer.cpp:299
2023-06-11 08:20:16 core-matter-server chip.BLE[126] ERROR No adapter available for new connection establishment
2023-06-11 08:20:17 core-matter-server chip.EM[126] INFO >>> [E:42692r S:38676 M:163334743] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:17 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:17 core-matter-server chip.EM[126] INFO <<< [E:42692r S:38676 M:175691774 (Ack:163334743)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:17 core-matter-server chip.IN[126] INFO (S) Sending msg 175691774 on secure session with LSID: 38676
2023-06-11 08:20:17 core-matter-server chip.EM[126] INFO >>> [E:4907r S:38677 M:201960534] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:17 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:17 core-matter-server chip.EM[126] INFO <<< [E:4907r S:38677 M:182901989 (Ack:201960534)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:17 core-matter-server chip.IN[126] INFO (S) Sending msg 182901989 on secure session with LSID: 38677
2023-06-11 08:20:17 core-matter-server chip.EM[126] INFO >>> [E:42692r S:38676 M:163334744 (Ack:175691774)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:17 core-matter-server chip.EM[126] INFO >>> [E:4907r S:38677 M:201960535 (Ack:182901989)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:22 core-matter-server chip.EM[126] INFO >>> [E:42694r S:38676 M:163334745] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:22 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:22 core-matter-server chip.EM[126] INFO <<< [E:42694r S:38676 M:175691775 (Ack:163334745)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:22 core-matter-server chip.IN[126] INFO (S) Sending msg 175691775 on secure session with LSID: 38676
2023-06-11 08:20:22 core-matter-server chip.EM[126] INFO >>> [E:4909r S:38677 M:201960536] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:22 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:22 core-matter-server chip.EM[126] INFO <<< [E:4909r S:38677 M:182901990 (Ack:201960536)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:22 core-matter-server chip.IN[126] INFO (S) Sending msg 182901990 on secure session with LSID: 38677
2023-06-11 08:20:22 core-matter-server chip.EM[126] INFO >>> [E:42694r S:38676 M:163334746 (Ack:175691775)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:22 core-matter-server chip.EM[126] INFO >>> [E:4909r S:38677 M:201960537 (Ack:182901990)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:27 core-matter-server chip.EM[126] INFO >>> [E:42696r S:38676 M:163334747] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:27 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:27 core-matter-server chip.EM[126] INFO <<< [E:42696r S:38676 M:175691776 (Ack:163334747)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:27 core-matter-server chip.IN[126] INFO (S) Sending msg 175691776 on secure session with LSID: 38676
2023-06-11 08:20:27 core-matter-server chip.EM[126] INFO >>> [E:4911r S:38677 M:201960538] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:27 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:27 core-matter-server chip.EM[126] INFO <<< [E:4911r S:38677 M:182901991 (Ack:201960538)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:27 core-matter-server chip.IN[126] INFO (S) Sending msg 182901991 on secure session with LSID: 38677
2023-06-11 08:20:27 core-matter-server chip.EM[126] INFO >>> [E:42696r S:38676 M:163334748 (Ack:175691776)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:27 core-matter-server chip.EM[126] INFO >>> [E:4911r S:38677 M:201960539 (Ack:182901991)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:31 core-matter-server chip.EM[126] INFO >>> [E:35849r S:38673 M:195517448] (S) Msg RX from 1:0000000000000006 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:31 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x500fa391 Peer = 01:0000000000000006
2023-06-11 08:20:31 core-matter-server chip.EM[126] INFO <<< [E:35849r S:38673 M:246811633 (Ack:195517448)] (S) Msg TX to 1:0000000000000006 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:31 core-matter-server chip.IN[126] INFO (S) Sending msg 246811633 on secure session with LSID: 38673
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO >>> [E:35849r S:38673 M:195517449 (Ack:246811633)] (S) Msg RX from 1:0000000000000006 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO >>> [E:42698r S:38676 M:163334749] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:32 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO <<< [E:42698r S:38676 M:175691777 (Ack:163334749)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:32 core-matter-server chip.IN[126] INFO (S) Sending msg 175691777 on secure session with LSID: 38676
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO >>> [E:4913r S:38677 M:201960540] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:32 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO <<< [E:4913r S:38677 M:182901992 (Ack:201960540)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:32 core-matter-server chip.IN[126] INFO (S) Sending msg 182901992 on secure session with LSID: 38677
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO >>> [E:42698r S:38676 M:163334750 (Ack:175691777)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:32 core-matter-server chip.EM[126] INFO >>> [E:4913r S:38677 M:201960541 (Ack:182901992)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:37 core-matter-server chip.EM[126] INFO >>> [E:42700r S:38676 M:163334751] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:37 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:37 core-matter-server chip.EM[126] INFO <<< [E:42700r S:38676 M:175691778 (Ack:163334751)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:37 core-matter-server chip.IN[126] INFO (S) Sending msg 175691778 on secure session with LSID: 38676
2023-06-11 08:20:37 core-matter-server chip.EM[126] INFO >>> [E:4915r S:38677 M:201960542] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:37 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:37 core-matter-server chip.EM[126] INFO <<< [E:4915r S:38677 M:182901993 (Ack:201960542)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:37 core-matter-server chip.IN[126] INFO (S) Sending msg 182901993 on secure session with LSID: 38677
2023-06-11 08:20:37 core-matter-server chip.EM[126] INFO >>> [E:42700r S:38676 M:163334752 (Ack:175691778)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:37 core-matter-server chip.EM[126] INFO >>> [E:4915r S:38677 M:201960543 (Ack:182901993)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:42 core-matter-server chip.EM[126] INFO >>> [E:42702r S:38676 M:163334753] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:42 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:42 core-matter-server chip.EM[126] INFO <<< [E:42702r S:38676 M:175691779 (Ack:163334753)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:42 core-matter-server chip.IN[126] INFO (S) Sending msg 175691779 on secure session with LSID: 38676
2023-06-11 08:20:42 core-matter-server chip.EM[126] INFO >>> [E:4917r S:38677 M:201960544] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:42 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:42 core-matter-server chip.EM[126] INFO <<< [E:4917r S:38677 M:182901994 (Ack:201960544)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:42 core-matter-server chip.IN[126] INFO (S) Sending msg 182901994 on secure session with LSID: 38677
2023-06-11 08:20:42 core-matter-server chip.EM[126] INFO >>> [E:42702r S:38676 M:163334754 (Ack:175691779)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:42 core-matter-server chip.EM[126] INFO >>> [E:4917r S:38677 M:201960545 (Ack:182901994)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:45 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2023-06-11 08:20:46 core-matter-server chip.EM[126] INFO >>> [E:15425r S:38672 M:32789367] (S) Msg RX from 1:0000000000000015 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x6894ab82 Peer = 01:0000000000000015
2023-06-11 08:20:46 core-matter-server chip.EM[126] INFO <<< [E:15425r S:38672 M:166038665 (Ack:32789367)] (S) Msg TX to 1:0000000000000015 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:46 core-matter-server chip.IN[126] INFO (S) Sending msg 166038665 on secure session with LSID: 38672
2023-06-11 08:20:46 core-matter-server chip.EM[126] INFO >>> [E:15425r S:38672 M:32789368 (Ack:166038665)] (S) Msg RX from 1:0000000000000015 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:46 core-matter-server chip.CTL[126] ERROR Discovery timed out
2023-06-11 08:20:46 core-matter-server chip.ZCL[126] ERROR Secure Pairing Failed
2023-06-11 08:20:46 core-matter-server matter_server.server.client_handler[126] ERROR [139860449458064] Error handling message: CommandMessage(message_id='244e975990a14f8096c521075acb0dae', command='commission_with_code', args={'code': '15604109093'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 154, in commission_with_code
    raise NodeCommissionFailed(
matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 34
2023-06-11 08:20:47 core-matter-server chip.EM[126] INFO >>> [E:42704r S:38676 M:163334755] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0x30322a4a Peer = 01:0000000000000019
2023-06-11 08:20:47 core-matter-server chip.EM[126] INFO <<< [E:42704r S:38676 M:175691780 (Ack:163334755)] (S) Msg TX to 1:0000000000000019 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:47 core-matter-server chip.IN[126] INFO (S) Sending msg 175691780 on secure session with LSID: 38676
2023-06-11 08:20:47 core-matter-server chip.EM[126] INFO >>> [E:4919r S:38677 M:201960546] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0001:05 (IM:ReportData)
2023-06-11 08:20:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 9224 milliseconds with SubscriptionId = 0xd7fa2493 Peer = 01:0000000000000017
2023-06-11 08:20:47 core-matter-server chip.EM[126] INFO <<< [E:4919r S:38677 M:182901995 (Ack:201960546)] (S) Msg TX to 1:0000000000000017 [F8A5] --- Type 0001:01 (IM:StatusResponse)
2023-06-11 08:20:47 core-matter-server chip.IN[126] INFO (S) Sending msg 182901995 on secure session with LSID: 38677
2023-06-11 08:20:47 core-matter-server chip.EM[126] INFO >>> [E:42704r S:38676 M:163334756 (Ack:175691780)] (S) Msg RX from 1:0000000000000019 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-06-11 08:20:47 core-matter-server chip.EM[126] INFO >>> [E:4919r S:38677 M:201960547 (Ack:182901995)] (S) Msg RX from 1:0000000000000017 [F8A5] --- Type 0000:10 (SecureChannel:StandaloneAck)
```

**Comment by trrevvorr** [comment]
I am running firmware 3.5.10 for my light strip - all three light strips are on the latest version.

**Comment by marcelveldt** [comment]
Looking at the log, the Matter server ws unable to discover the device using a mDNS lookup. This can have a ton of reasons unfortunately but in 90% if the cases this is due to the IPv6 stack somehow misbehaving on the host (and thus Matter server container). Also it seems that the Nanoleaf devices are the most picky ones in this regards, not sure why.

A few things to try:

1) Reboot HAOS completely befor pairing
2) Set your Ipv6 configuration in the HAOS to static and then back to DHCP.

If that does not help we can proceed with some further testing by trying to ping the device from Homeassistant.

**Comment by trrevvorr** [comment]
Doing ha hard reboot via Settings > System > Power Button in top right > Advanced Options > Reboot System did the trick! Light strip paired on the first attempt after the reboot.
