### ISSUE TITLE
ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch

### ISSUE THREAD

**Issue by lboue** [home-assistant-libs/python-matter-server#322]
Do you know where this _Version mismatch_ error could come from?

### Env

- Home Assistant 2023.6.1
- Supervisor 2023.06.1
- Operating System 10.2
- Frontend 20230608.0 - latest
- Matter Server: 4.6.0 

### Pairing Tasmota device
Start pairing Tasmota device with Matter enabled with HomeAsssitant

![image](https://github.com/home-assistant-libs/python-matter-server/assets/938089/180f3180-5c9d-4dcf-bff9-e1ee60dde1e3)

### Result/Error

`ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
`

```
2023-06-12 11:42:08 core-matter-server chip.IN[126] INFO (S) Sending msg 159561370 on secure session with LSID: 4081
2023-06-12 11:42:09 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:09 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:09 core-matter-server chip.IN[126] INFO (S) Sending msg 159561370 on secure session with LSID: 4081
2023-06-12 11:42:09 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:09 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:09 core-matter-server chip.IN[126] INFO (S) Sending msg 159561370 on secure session with LSID: 4081
2023-06-12 11:42:09 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:09 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:10 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:10 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:10 core-matter-server chip.IN[126] INFO (S) Sending msg 159561370 on secure session with LSID: 4081
2023-06-12 11:42:10 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:10 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:11 core-matter-server chip.IN[126] INFO (S) Sending msg 159561370 on secure session with LSID: 4081
2023-06-12 11:42:11 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:11 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:12 core-matter-server chip.EM[126] ERROR Failed to Send CHIP MessageCounter:159561370 on exchange 28937i sendCount: 4 max retries: 4
2023-06-12 11:42:12 core-matter-server chip.IN[126] ERROR Secure transport received message, but failed to decode/authenticate it, discarding
2023-06-12 11:42:12 core-matter-server chip.IN[126] ERROR Failed to decode packet header: src/transport/raw/MessageHeader.cpp:142: CHIP Error 0x000000A7: Version mismatch
2023-06-12 11:42:15 core-matter-server chip.SC[126] INFO SecureSession[0xffff9c039b60]: Moving from state 'kActive' --> 'kDefunct'
2023-06-12 11:42:15 core-matter-server chip.DMG[126] ERROR Time out! failed to receive report data from Exchange: 28937i
2023-06-12 11:42:15 core-matter-server matter_server.server.client_handler[126] ERROR [281473602105296] Error handling message: CommandMessage(message_id='764ceedf6c0f4b12a865749c96eadd62', command='commission_with_code', args={'code': 'MT:00000-O913FNHV7.320'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 290, in interview_node
    await self.chip_controller.Read(
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 1025, in Read
    return await future
           ^^^^^^^^^^^^
chip.exceptions.ChipStackError: Chip Stack Error 50
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 159, in commission_with_code
    await self.interview_node(node_id)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 295, in interview_node
    raise NodeInterviewFailed(f"Failed to interview node {node_id}") from err
matter_server.common.errors.NodeInterviewFailed: Failed to interview node 4
```

### Full log
Full log [2023-06-12-11h42-core-matter-server.log](https://github.com/home-assistant-libs/python-matter-server/files/11721004/2023-06-12-11h42-core-matter-server.log)

**Comment by lboue** [comment]
Pairing works fine with Apple Home.

**Comment by marcelveldt** [comment]
closing this due to no response
