### ISSUE TITLE
Error unloading entry Matter for sensor

### ISSUE THREAD

**Issue by lboue** [home-assistant-libs/python-matter-server#353]
# Summary
I am facing an issue with the Matter server daemon since I renamed devices associated with a Matter bridge.
I find the error Error unloading entry Matter for sensor in the logs:
`Error unloading entry Matter for sensor`

I already restarted Matter server without success.
Could you help me fix this issue?

![image](https://github.com/home-assistant-libs/python-matter-server/assets/938089/c85db289-c0f6-4261-880a-b87fccfa3780)

## Env

- Home Assistant 2023.7.1
- Supervisor 2023.07.1
- Operating System 10.2
- Frontend 20230705.1
- Matter Server 4.8.2
- Aqara Hub E1 4.0.2

## Errors

```
Logger: homeassistant.config_entries
Source: components/matter/entity.py:109
First occurred: 9:38:48 PM (1 occurrences)
Last logged: 9:38:48 PM

Error unloading entry Matter for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 802, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1030, in async_remove
    await self.async_will_remove_from_hass()
  File "/usr/src/homeassistant/homeassistant/components/matter/entity.py", line 109, in async_will_remove_from_hass
    unsub()
  File "/usr/local/lib/python3.11/site-packages/matter_server/client/client.py", line 99, in unsubscribe
    self._subscribers[key].remove(callback)
ValueError: list.remove(x): x not in list
```

```
Logger: aiohttp.server
Source: components/matter/diagnostics.py:60
First occurred: 9:51:36 PM (2 occurrences)
Last logged: 10:05:52 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 268, in get
    data = await info.device_diagnostics(hass, config_entry, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/matter/diagnostics.py", line 60, in async_get_device_diagnostics
    server_diagnostics = await matter.matter_client.get_diagnostics()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/client/client.py", line 345, in get_diagnostics
    data = await self.send_command(APICommand.SERVER_DIAGNOSTICS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/client/client.py", line 293, in send_command
    raise InvalidState("Not connected")
matter_server.client.exceptions.InvalidState: Not connected
```

## Matter server log file

[core_matter_server_2023-07-07T20-10-58.885Z.log](https://github.com/home-assistant-libs/python-matter-server/files/11985564/core_matter_server_2023-07-07T20-10-58.885Z.log)

**Comment by marcelveldt** [comment]
Can you tell me the exact steps to reproduce this ?
