### ISSUE TITLE
Can't set nullable attribute to null

### ISSUE THREAD

**Issue by joebandenburg** [home-assistant-libs/python-matter-server#434]
I'm running the latest server via docker and trying to use the client library to set the `LevelControl.onLevel` attribute to `null`:

```python
from matter_server.client import client
from matter_server.common.helpers import util
from chip.clusters import Objects

on_level = util.create_attribute_path_from_attribute(1, Objects.LevelControl.Attributes.OnLevel)

async with aiohttp.ClientSession() as session:
        async with client.MatterClient('ws://phobos:5580/ws', session) as matter_client:
            init_ready = asyncio.Event()
            task = asyncio.create_task(matter_client.start_listening(init_ready))
            await init_ready.wait()
            await matter_client.write_attribute(1, on_level, None)
```

This raises the following exception on the server:
```
2023-11-19 16:59:28 phobos matter_server.server.client_handler[1] ERROR [140017411249488] Error handling message: CommandMessage(message_id='12cdc146a06e4aab89a763c6afe4d353', command='write_attribute', args={'node_id': 1, 'attribute_path': '1/8/17', 'value': None})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 427, in write_attribute
    return await self.chip_controller.WriteAttribute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 890, in WriteAttribute
    ClusterAttribute.WriteAttributes(
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/Attribute.py", line 992, in WriteAttributes
    tlv = attr.Attribute.ToTLV(None, attr.Data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/ClusterObjects.py", line 297, in ToTLV
    cls.attribute_type.PutFieldToTLV(tag,
  File "/usr/local/lib/python3.11/site-packages/chip/clusters/ClusterObjects.py", line 83, in PutFieldToTLV
    raise ValueError(
ValueError: Field . was not optional, but encountered None
```

According to the CHIP SDK, this attribute is nullable:

```python
@dataclass
class LevelControl(Cluster):
    id: typing.ClassVar[int] = 0x00000008

    # ...

    onLevel: 'typing.Union[Nullable, uint]' = None

    #...
    
    class Attributes:
       #...

        @dataclass
        class OnLevel(ClusterAttributeDescriptor):
            @ChipUtility.classproperty
            def cluster_id(cls) -> int:
                return 0x00000008

            @ChipUtility.classproperty
            def attribute_id(cls) -> int:
                return 0x00000011

            @ChipUtility.classproperty
            def attribute_type(cls) -> ClusterObjectFieldDescriptor:
                return ClusterObjectFieldDescriptor(Type=typing.Union[Nullable, uint])

            value: 'typing.Union[Nullable, uint]' = NullValue
```

Is this a bug or is there some other way to clear the value of a nullable attribute?

**Comment by joebandenburg** [comment]
Note that I also tried setting the attribute to `NullValue`, which had the same effect.

**Comment by joebandenburg** [comment]
My guess from looking at the code is that the server needs to convert `None` to `NullValue` before passing it to `self.chip_controller.WriteAttribute`.

**Comment by marcelveldt** [comment]
Yeah we'll need to adjust the helper function for this scenario.

**Comment by joebandenburg** [comment]
I've created #437 to fix. Any feedback welcome.
