### ISSUE TITLE
Comission new device already on Apple TV Thread network?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#444]
Not sure if this scenario makes sense or not, but this is what I would like to achieve:

I have a Matter Thread device already paired with Apple Home using an Apple TV.

Now I want to commission the same device to the Python Matter Server in order to control the device from this ecosystem rather than the Apple ecosystem.

I would prefer not to use another OpenThread Boarder Router with the Python Matter Server, but use the Thread network created by Apple Tv.

I opened the settings for the device in the Apple Home app and selected "Turn On Pairing Mode". I then get a Setup code in the format "XXXX-YYY-ZZZZ".

Then I tried to add the device to  Python Matter Server using this message:

    {
        "message_id": "6",
        "command": "commission_with_code",
        "args": {
            "code": "05347804358"
        }
    }

But, that failed with:

    {
      "message_id": "6",
      "error_code": 1,
      "details": "Commission with code failed for node 5"
    }

In the Python Matter Server, I got the following log messages:

2023-12-02 09:34:17 matter-server matter_server.server.helpers.paa_certificates[1] INFO Fetched 0 PAA root certificates from Git.
2023-12-02 09:34:20 matter-server matter_server.server.client_handler[1] ERROR [547584145360] Error handling message: CommandMessage(message_id='6', command='commission_with_code', args={'code': '05347804358'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 167, in commission_with_code
    raise NodeCommissionFailed(
matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 5
2023-12-02 09:34:20 matter-server PersistentStorage[1] INFO SetSdkKey: f/1/s/0000000000000005 = b'\x150\x03\x10\x8f\x03\x81s8\xfd\x13L\r52\xe4Z\xf7\xcd\xd10\x04 \x0f\x82\xba\xd0()\x89\xa4\x80\xc5\x98\x7f\xa4\x0e\x15\xed\x8d\x1f\x99V\xd2\x08\xd5P\x0cf\x92{\x9ezE\xf50\x05\x0c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18'
2023-12-02 09:34:20 matter-server PersistentStorage[1] INFO Committing...
2023-12-02 09:34:20 matter-server PersistentStorage[1] INFO SetSdkKey: g/s/jwOBczj9E0wNNTLkWvfN0Q== = b'\x15$\x01\x01$\x02\x05\x18'
2023-12-02 09:34:20 matter-server PersistentStorage[1] INFO Committing...
2023-12-02 09:34:20 matter-server PersistentStorage[1] INFO SetSdkKey: g/sri = b'\x16\x15$\x01\x01$\x02\x02\x18\x15$\x01\x01$\x02\x05\x18\x18'
2023-12-02 09:34:20 matter-server PersistentStorage[1] INFO Committing...
2023-12-02 09:34:27 matter-server chip.CTL[1] ERROR Commissioning discovery over BLE failed: src/platform/Linux/bluez/ChipDeviceScanner.cpp:173: CHIP Error 0x00000032: Timeout
2023-12-02 09:34:27 matter-server chip.-[1] ERROR src/platform/Linux/bluez/ChipDeviceScanner.cpp:173: CHIP Error 0x00000032: Timeout at src/controller/SetUpCodePairer.cpp:324
2023-12-02 09:34:27 matter-server chip.BLE[1] ERROR BLE scan error: src/platform/Linux/bluez/ChipDeviceScanner.cpp:173: CHIP Error 0x00000032: Timeout

**Comment by marcelveldt** [comment]
Sorry, we do not have the capacity to provide user support here. This library is meant to be consumed by other projects (like Home Assistant) and thus the support we offer here is only towards developers.
