### ISSUE TITLE
Error trying to run the python-matter-server container

### ISSUE THREAD

**Issue by jtenniswood** [home-assistant-libs/python-matter-server#460]
I'm trying to run the python-matter-server container, and even with an empty data folder, I get this error...

```
[1702072175.700647][1:1] CHIP:CTL: Setting attestation nonce to random value
[1702072175.700757][1:1] CHIP:CTL: Setting CSR nonce to random value
[1702072175.702008][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1702072175.702170][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1702072175.702319][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_config.ini
[1702072175.702397][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_counters.ini
[1702072175.702633][1:1] CHIP:DL: writing settings to file (/data/chip_counters.ini-r8DGDf)
[1702072175.702910][1:1] CHIP:DL: renamed tmp file to file (/data/chip_counters.ini)
[1702072175.702932][1:1] CHIP:DL: NVS set: chip-counters/reboot-count = 15 (0xF)
[1702072175.704147][1:1] CHIP:DL: Got Ethernet interface: enp0s31f6
[1702072175.705150][1:1] CHIP:DL: Found the primary Ethernet interface:enp0s31f6
[1702072175.706142][1:1] CHIP:DL: Got WiFi interface: wlp0s20f3
[1702072175.706175][1:1] CHIP:DL: Failed to reset WiFi statistic counts
2023-12-08 21:49:35 server PersistentStorage[1] WARNING Initializing persistent storage from file: /data/chip.json
2023-12-08 21:49:35 server PersistentStorage[1] WARNING Loading configuration from /data/chip.json...
2023-12-08 21:49:35 server PersistentStorage[1] INFO SetSdkKey: g/gcc = b'\x9e\xe3\xb7\t'
2023-12-08 21:49:35 server PersistentStorage[1] INFO Committing...
2023-12-08 21:49:35 server PersistentStorage[1] INFO SetSdkKey: g/gdc = b'\xbd,\xe7\x03'
2023-12-08 21:49:35 server PersistentStorage[1] INFO Committing...
Traceback (most recent call last):
  File "/usr/local/bin/matter-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/__main__.py", line 81, in main
    server = MatterServer(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 74, in __init__
    self.stack = MatterStack(self)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/stack.py", line 32, in __init__
    self._chip_stack = ChipStack(
                       ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipStack.py", line 64, in wrapper
    instance[0] = cls(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipStack.py", line 271, in __init__
    res.raise_on_error()
  File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/system/SystemLayerImplSelect.cpp:376: CHIP Error 0x000000C1: Endpoint pool full
```

Any suggestions as it was running fine yesterday.

**Comment by zerotohero** [comment]
I was just trying to set this up for the first time and have the exact same issue.

**Comment by marcelveldt** [comment]
Shut down some containers and try again.

**Comment by b1t-hunter** [comment]
Fixed this issue by increasing the `net.ipv4.igmp_max_memberships` value above the default of 20 on the docker host, like so:

```bash
`echo "net.ipv4.igmp_max_memberships=100" >> /etc/sysctl.d/99-custom.conf`
```
