### ISSUE TITLE
Consider upgrading Docker image from bullseye to bookworm (for OpenSSL 3)

### ISSUE THREAD

**Issue by Sjors** [home-assistant-libs/python-matter-server#464]
I'm experimenting with running the Matter (development) server without Docker on my Ubuntu 23.10 machine (which also runs Home Assistant core without Docker).

I got an error about missing `libcrypto.so.1.1`, which I was able to [work around](https://stackoverflow.com/a/73604364/313633). But such workarounds can be dangerous, so I wouldn't recommend it.

```
Traceback (most recent call last):
  File "/home/homeassistant/.local/bin/matter-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/homeassistant/.local/pipx/venvs/python-matter-server/lib/python3.11/site-packages/matter_server/server/__main__.py", line 81, in main
    server = MatterServer(
             ^^^^^^^^^^^^^
  File "/home/homeassistant/.local/pipx/venvs/python-matter-server/lib/python3.11/site-packages/matter_server/server/server.py", line 74, in __init__
    self.stack = MatterStack(self)
                 ^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.local/pipx/venvs/python-matter-server/lib/python3.11/site-packages/matter_server/server/stack.py", line 29, in __init__
    chip.native.Init()
  File "/home/homeassistant/.local/pipx/venvs/python-matter-server/lib/python3.11/site-packages/chip/native/__init__.py", line 197, in Init
    _GetLibraryHandle(False).pychip_CommonStackInit(ctypes.c_char_p(params))
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.local/pipx/venvs/python-matter-server/lib/python3.11/site-packages/chip/native/__init__.py", line 181, in _GetLibraryHandle
    _nativeLibraryHandle = ctypes.CDLL(FindNativeLibraryPath())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

Modern Debian (>=12), Ubuntu (>=22.04) and MacOs all use OpenSSL 3, and 1.1 seems to be [EOL](https://endoflife.date/openssl).

If I understand the error correctly the published wheels would also need to be built with a newer Docker image. Though the [Github workflow](https://github.com/home-assistant-libs/chip-wheels/blob/main/.github/workflows/build.yaml) linked to in the README seems to already use Ubuntu 22.10, which comes with OpenSSL 3, so I'm a bit puzzled there.

**Comment by marcelveldt** [comment]
You shouldn't be running the Matter server directly. Only when you are developing that could be considered but for other cases I really recommend you to not run it this way, we wont provide support. Just run Home Assistant OS in a VM or the docker container (that still requires changes to your host OS).

**Comment by marcelveldt** [comment]
As for upgrading the base image, we will do that at some point but keep in mind we're dependent of many external factors, the biggest being the whole Matter SDK.
