### ISSUE TITLE
Issue adding multiple matter wifi bulbs on 5.1.2 but works on 5.0.3

### ISSUE THREAD

**Issue by ldesplat** [home-assistant-libs/python-matter-server#482]
I run an unsupported setup with HA in docker and python-matter-server in docker with host networking so not expecting any support here but after going through issues I was able to diagnose my issue on 5.1.1 and eventually 5.1.2 a little bit.

I am adding two OREIN wifi matter bulbs one after another in HA. First one works just fine, second one always fails but then HA starts controlling either one randomly. After going through issues, I just decided to use the container of 5.0.3 and everything works correctly from HA side, resolving the issue. I did encounter the issue in both 5.1.1 and 5.1.2 with slightly different symptoms. 5.1.1 would just override (50/50) and 5.1.2 would completely break the integration with first light and second light would not work.

Fresh Logs from 5.1.2 fresh install (deleted data directory completely and started a fresh container) with me enrolling the bulbs
```
...
2023-12-27 19:45:42 rb FabricAdmin[1] WARNING Allocating new controller with CaIndex: 1, FabricId: 0x0000000000000001, NodeId: 0x000000000001B669, CatTags: []
2023-12-27 19:45:42 rb matter_server.server.device_controller[1] INFO Loaded 0 nodes from stored configuration
2023-12-27 19:45:42 rb matter_server.server.vendor_info[1] INFO Loading vendor info from storage.
2023-12-27 19:45:42 rb matter_server.server.vendor_info[1] INFO Loaded 0 vendors from storage.
2023-12-27 19:45:42 rb matter_server.server.vendor_info[1] INFO Fetching the latest vendor info from DCL.
2023-12-27 19:45:42 rb matter_server.server.vendor_info[1] INFO Fetched 100 vendors from DCL.
2023-12-27 19:45:42 rb matter_server.server.vendor_info[1] INFO Saving vendor info to storage.
2023-12-27 19:49:43 rb matter_server.server.device_controller[1] INFO Starting Matter commissioning with code using Node ID 1.
2023-12-27 19:49:48 rb matter_server.server.device_controller[1] INFO Matter commissioning of Node ID 1 successful.
2023-12-27 19:49:48 rb matter_server.server.device_controller[1] INFO Interviewing node: 1
2023-12-27 19:49:51 rb matter_server.server.device_controller.[node 1][1] INFO Setting up attributes and events subscription.
2023-12-27 19:49:52 rb matter_server.server.device_controller.[node 1][1] INFO Subscription succeeded
2023-12-27 19:49:52 rb matter_server.server.device_controller[1] INFO Commissioning of Node ID 1 completed.
2023-12-27 19:49:57 rb matter_server.server.device_controller.[node 1][1] INFO Setting up attributes and events subscription.
2023-12-27 19:50:01 rb matter_server.server.device_controller.[node 1][1] INFO Subscription succeeded


2023-12-27 19:52:26 rb matter_server.server.device_controller[1] INFO Starting Matter commissioning with code using Node ID 1.
2023-12-27 19:52:30 rb chip.CTL[1] ERROR Failed to perform commissioning step 27
2023-12-27 19:52:30 rb matter_server.server.client_handler[1] ERROR [547813155600] Error handling message: CommandMessage(message_id='297e9e05d949455d9b5c58744c950ed2', command='commission_with_code', args={'code': 'MT:OI7K2D1V01F28-6J-00'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 197, in commission_with_code
    raise NodeCommissionFailed(
matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 1

2023-12-27 20:18:53 rb chip.EM[1] ERROR Failed to Send CHIP MessageCounter:260363246 on exchange 32013i sendCount: 4 max retries: 4
```
Last log entry is me trying to turn on/off the first light via HA.

Knowing nothing at all, it feels like Node ID is being reused.

**Comment by marcelveldt** [comment]
First of all: This repo is not for user support, use the HA core repository for that or join our discord server. This is clearly stated when you press that new issue button.

Second of all: versions 5.1.x are still beta versions and we're testing out some stuff. If you decide to ignore our recommendations to not run the matter server yourself in docker, you should at least make sure to run the version that is used by the official matter add-on: https://github.com/home-assistant/addons/blob/master/matter_server/build.yaml#L3

We have a task on our backlog to adjust our build scripts so that beta releases will not be pushed to the stable tag on docker. Until then, you will have to find out yourself if its a beta or stable version and not automatically update.

As for the Node ID being reused, I highly doubt that but could be regression in last beta version. Thanks for the hint.

**Comment by marcelveldt** [comment]
Ah, your hunch was actually right: There's a regression in last version where the node id is indeed re-purposed.
