### ISSUE TITLE
Cleaner log for timeouts

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#522]
I think one should expect devices to be offline from time to time.

This could be very true for devices like smart light bulbs etc., where you may have a physical switch that is not always on.

Currently devices that are offline causes a quite verbose log like this:

2024-02-01 09:34:21 matter-server chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2024-02-01 09:34:35 matter-server chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000004]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout
2024-02-01 09:34:35 matter-server matter_server.server.client_handler[1] ERROR [548172696912] SDK Error during handling message: CommandMessage(message_id='90', command='device_command', args={'node_id': 4, 'endpoint_id': 1, 'cluster_id': 768, 'command_name': 'MoveToHueAndSaturation', 'payload': {'hue': 0, 'saturation': 238, 'transitionTime': 0, 'optionsMask': 0, 'optionsOverride': 0}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 503, in send_device_command
    return await self.chip_controller.SendCommand(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 834, in SendCommand
    device = self.GetConnectedDeviceSync(nodeid, timeoutMs=interactionTimeoutMs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 779, in GetConnectedDeviceSync
    returnErr.raise_on_error()
  File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout

I think it would be better with a bit cleaner log for this scenario as this will make it easier to spot real unexpected issues.

**Comment by marcelveldt** [comment]
I don't agree that we should go hide things from the log. This is where a log is for, log important things that happened. In this case a timeout issue. What we could have done in this case is not try the command at all if the node is known to be offline, that is an actual improvement. But hiding things from logs? No, bad idea.

**Comment by olavt** [comment]
I was not suggesting to remove the log entry, but make it cleaner. Is a stack trace really needed?

**Comment by marcelveldt** [comment]
For now (while we're still developing) YES the full stacktrace is needed.
Once we mature, we will bring it down
