### ISSUE TITLE
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value?

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#565]
Not sure what triggered this error, but it might be a bug.

It would be great if the noise level for expected errors could be reduced in the log as well. A warning or info message would be sufficient.

A couple of this error entries below are simply caused by a light bulb being turned off (no power).

2024-02-18 04:51:22 hemsedal-controller matter_server.server.client_handler[1] ERROR [547320470672] Error handling message: CommandMessage(message_id='3902', command='device_command', args={'node_id': 5, 'endpoint_id': 1, 'cluster_id': 768, 'command_name': 'MoveToHueAndSaturation', 'payload': {'hue': 14, 'saturation': 152, 'transitionTime': 10, 'optionsMask': 0, 'optionsOverride': 0}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 193, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 555, in send_device_command
    raise NodeNotReady(f"Node {node_id} is not (yet) available.")
matter_server.common.errors.NodeNotReady: Node 5 is not (yet) available.
2024-02-18 04:51:22 hemsedal-controller matter_server.server.client_handler[1] ERROR [547320470672] Error handling message: CommandMessage(message_id='3903', command='device_command', args={'node_id': 5, 'endpoint_id': 1, 'cluster_id': 6, 'command_name': 'On', 'payload': None})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 193, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 555, in send_device_command
    raise NodeNotReady(f"Node {node_id} is not (yet) available.")
matter_server.common.errors.NodeNotReady: Node 5 is not (yet) available.
2024-02-18 04:52:22 hemsedal-controller matter_server.server.client_handler[1] ERROR [547320470672] Error handling message: CommandMessage(message_id='3904', command='device_command', args={'node_id': 5, 'endpoint_id': 1, 'cluster_id': 768, 'command_name': 'MoveToHueAndSaturation', 'payload': {'hue': 14, 'saturation': 152, 'transitionTime': 10, 'optionsMask': 0, 'optionsOverride': 0}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 193, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 555, in send_device_command
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value

**Comment by marcelveldt** [comment]
At this stage we are still developing so we make the exceptions as verbose as possible as it helps us debugging issues so I'm not particular interested in reducing. What you can noise is valid info while trying to investigate an issue.

The issue you are describing is not one I have ever seen. Please try to describe how I can reproduce this and it will get looked at, otherwise this is most probably just some random fluke or your client sent the wrong info

**Comment by olavt** [comment]
It actually looks like the error message "error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value" is from Docker and not the log entries from Python Matter Server.
