### ISSUE TITLE
5.7.0: Fails to start with "CHIP Error 0x000000C1: Endpoint pool full"

### ISSUE THREAD

**Issue by bootc** [home-assistant-libs/python-matter-server#601]
I upgraded from 5.6.0 to 5.7.0 (using the Docker image) and PMS fails to start in my environment:

```
2024-02-29 16:12:32 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Logging...
[1709223152.260661][1:1] CHIP:CTL: Setting attestation nonce to random value
[1709223152.260913][1:1] CHIP:CTL: Setting CSR nonce to random value
2024-02-29 16:12:32 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Controller Stack...
2024-02-29 16:12:32 (MainThread) CHIP_ERROR [chip.native.DL] Failed to get WiFi interface
2024-02-29 16:12:32 (MainThread) CHIP_ERROR [chip.native.DL] Failed to reset WiFi statistic counts
2024-02-29 16:12:32 (MainThread) WARNING [PersistentStorage] Initializing persistent storage from file: /data/chip.json
2024-02-29 16:12:32 (MainThread) WARNING [PersistentStorage] Loading configuration from /data/chip.json...
2024-02-29 16:12:32 (MainThread) ERROR [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/matter-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/__main__.py", line 171, in main
    server = MatterServer(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 115, in __init__
    self.stack = MatterStack(self)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/stack.py", line 98, in __init__
    self._chip_stack = ChipStack(
                       ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipStack.py", line 64, in wrapper
    instance[0] = cls(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipStack.py", line 271, in __init__
    res.raise_on_error()
  File "/usr/local/lib/python3.11/site-packages/chip/native/__init__.py", line 67, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/system/SystemLayerImplSelect.cpp:376: CHIP Error 0x000000C1: Endpoint pool full
```

Downgrading to 5.6.0 again allows the server to come back up again.

**Comment by Scope666** [comment]
Same thing, but I got shot down because I run in Docker.

**Comment by marcelveldt** [comment]
Sorry, we do not provide user support here, nor do we officially support the docker image to run the matter server.
So basically you're on your own with regards to support. I trult advise to run the Matter server add-on. You can even run HA as virtual machine if you want, we provide several images for that.

We did see this in the past and in those cases it was related to the amount of containers (running on host networking). If the issue dissapears when you shutdown a few containers there's a hint there. 

Something to try is maybe use a macvlan/bridge for the networking part. As you run docker yourself, you have a bit more influence on that.

**Comment by Scope666** [comment]
For what it's worth, switching to BR0 on my Unraid box gets 5.7.0 to work.  Not sure what changed between 5.6 and 5.7, but I can live with this.

**Comment by marcelveldt** [comment]
Goof to know that switching to bridge networking works. Maybe the recent additions for mdns browsing was just enough to push it over the edge, there's a lot of sockets opened in the SDK and its surroundings.

**Comment by bootc** [comment]
In this case I'm running in Kubernetes, and the container uses host networking so it can get at the real network interfaces. If the issue is the number of interfaces, can't the SDK be adjusted to deal with that again like it used to work?

Failing that I'd have to set up something like Multus with OVN so the pod gets a real IP on my local network via a bridge. That's a lot of extra complication for something that used to just work.

**Comment by fcastilloec** [comment]
I'm using Home Assistant Supervised with the Matter add-on and seeing this error as well, I'm not running any additional software in Docker, just Home Assistant.
The workaround described here doesn't work for me, since I cannot change the network settings of a specific add-on in Home Assistant.
I've reported this error directly on the Home Assistant add-on repository, hopefully, it won't be closed like all other issues mentioning this error since that one is a supported installation method.
https://github.com/home-assistant/addons/issues/3496

**Comment by marcelveldt** [comment]
@fcastilloec I'm sorry but supervised is also not a supported installation method. Everywhere in our documentation we mention that the ONLY officially supported method is Home Assistant OS with the Matter server add-on.

**Comment by marcelveldt** [comment]
Actually we found something so this will be fixed in the next update. Still the comments about the supported setup remain. Matter (especially with Thread) is complicated and has a lot of dependencies on the host OS. Home Assistant OS is carefully tweaked to handle that optimally. This is not just another container you can start and forget, hence all our precautions.

**Comment by bootc** [comment]
I can confirm 5.8.0 works, thanks!
