### ISSUE TITLE
Commissioning of a ContactSensor device results in exception object has no attribute '_device'

### ISSUE THREAD

**Issue by jculbert** [home-assistant-libs/python-matter-server#68]
I'm glad I found this great project. I'm working on DIY matter devices and want to connect them to Home Assistant.

I'm working with a Silicon Labs EFR32 board and the connectedhomeip chef ContactSensor example.

In commissioning my device the exception below occurs.

The root cause seems to be that binary_sensor.py is trying to access the device with self._device in function _update_from_device(). If I change it to self._device_type_instance the problem is fixed. I think the same issue exists in switch.py.

python-matter-server commit: ccb6d292dc896418de0269f3accaef0c3aef27ed
connectedhomeip commit: a1643eee5ef5534d494ae205bb586b4a9cbfee23

Exception trace from log:
ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform matter_experimental
2022-09-09T12:17:22.418462445-04:00 Traceback (most recent call last):
2022-09-09T12:17:22.418478058-04:00   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
2022-09-09T12:17:22.418489958-04:00     await asyncio.gather(*tasks)
2022-09-09T12:17:22.418529710-04:00   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
2022-09-09T12:17:22.418546577-04:00     await entity.add_to_platform_finish()
2022-09-09T12:17:22.418569721-04:00   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
2022-09-09T12:17:22.418579107-04:00     await self.async_added_to_hass()
2022-09-09T12:17:22.418587910-04:00   File "/config/custom_components/matter_experimental/entity.py", line 77, in async_added_to_hass
2022-09-09T12:17:22.418595969-04:00     await self.init_matter_device()
2022-09-09T12:17:22.418603898-04:00   File "/config/custom_components/matter_experimental/entity.py", line 64, in init_matter_device
2022-09-09T12:17:22.418612912-04:00     self._update_from_device()
2022-09-09T12:17:22.418621625-04:00   File "/config/custom_components/matter_experimental/binary_sensor.py", line 47, in _update_from_device
2022-09-09T12:17:22.418630118-04:00     self._attr_is_on = self._device.get_cluster(clusters.BooleanState).stateValue
2022-09-09T12:17:22.418650088-04:00 AttributeError: 'MatterBinarySensor' object has no attribute '_device'

**Comment by balloob** [comment]
Good catch. I've mainly been focused on lights as that's what I had on the dev firmware. I put a fix here #72

If you would want to help development, we need some [fixtures](https://github.com/home-assistant-libs/python-matter-server/tree/main/tests/fixtures/nodes) for binary sensor and switch to ensure this works.

**Comment by jculbert** [comment]
Sure, I can take this on. I'll start with a fixture for binary sensor.
