### ISSUE TITLE
Commissioning of a ContactSensor device results in exception 'NoneType' object has no attribute 'stateValue'

### ISSUE THREAD

**Issue by jculbert** [home-assistant-libs/python-matter-server#69]
I'm working with a Silicon Labs EFR32 board and the connectedhomeip chef ContactSensor example.

In commissioning my device the exception below occurs.

The root cause seems to be that ContactSensor in devices_types.py is missing the cluster BooleanState. If I add this the problem is fixed.

python-matter-server commit: ccb6d292dc896418de0269f3accaef0c3aef27ed
connectedhomeip commit: a1643eee5ef5534d494ae205bb586b4a9cbfee23
Home Assistant version: 2022.8.5

Exception trace from log:
2022-09-09 12:58:29.459 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform matter_experimental
2022-09-09T12:58:29.460750524-04:00 Traceback (most recent call last):
2022-09-09T12:58:29.460779133-04:00   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
2022-09-09T12:58:29.460801700-04:00     await asyncio.gather(*tasks)
2022-09-09T12:58:29.460822178-04:00   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
2022-09-09T12:58:29.460876646-04:00     await entity.add_to_platform_finish()
2022-09-09T12:58:29.460898320-04:00   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
2022-09-09T12:58:29.460916537-04:00     await self.async_added_to_hass()
2022-09-09T12:58:29.460935921-04:00   File "/config/custom_components/matter_experimental/entity.py", line 77, in async_added_to_hass
2022-09-09T12:58:29.460955333-04:00     await self.init_matter_device()
2022-09-09T12:58:29.460973679-04:00   File "/config/custom_components/matter_experimental/entity.py", line 64, in init_matter_device
2022-09-09T12:58:29.460992991-04:00     self._update_from_device()
2022-09-09T12:58:29.461011986-04:00   File "/config/custom_components/matter_experimental/binary_sensor.py", line 47, in _update_from_device
2022-09-09T12:58:29.461030620-04:00     self._attr_is_on = self._device_type_instance.get_cluster(clusters.BooleanState).stateValue
2022-09-09T12:58:29.461048645-04:00 AttributeError: 'NoneType' object has no attribute 'stateValue'

**Comment by balloob** [comment]
Good point. This was fixed on Aug 16 in https://github.com/project-chip/connectedhomeip/pull/21900 but we're still on https://github.com/project-chip/connectedhomeip/tree/a1643eee5e/ from Aug 10.

**Comment by jculbert** [comment]
Thanks. Now I see that file devices_types.py is generated by a script that uses connectedhomeip content.

I have a somewhat related question, not sure if this is the right place... From the code I see that CLUSTER_OBJECT_VERSION is set equal to a connectedhomeip commit and is used in the interview process. I take it mean that python-matter-server instances work with a particular connectionhomeip commit. If so, can you expand briefly on what is going on here?

**Comment by balloob** [comment]
The Matter SDK doesn't publish standalone wheels yet of their Python environment, so we copy some of those files over and generate some files based on it (see #75 for example). 

Both client and server need to have the same version for messages to be seamlessly serialize/deserialize.
