### ISSUE TITLE
OSError: [Errno 105] No buffer space available

### ISSUE THREAD

**Issue by JohnGalt1717** [home-assistant-libs/python-matter-server#702]
I'm running matter server like this:

```
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: always
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./data:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host  
```

On fully patched Ubuntu Server 22.04

The logs show:

```
2024-05-15 01:58:16.969 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.start()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 179, in start
    self._aiozc = AsyncZeroconf(ip_version=IPVersion.All)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/asyncio.py", line 166, in __init__
    self.zeroconf = zc or Zeroconf(
                          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 180, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

```

when I docker exec into it and install websocat I get a permission denied on this: websocat ws://localhost:5580/ws

What am I doing wrong?

**Comment by marcelveldt** [comment]
First of all: Are you a developer or Home Assistant user ? Our issue report form indicates that for user support, please use the HA issue tracker so we can leave issues reported here for library consumers/developers.

Secondly, running the Matter server in docker yourself is on your own risk. 
Small guess based on your log pasted above: Did you setup IPv6 on your host ?

**Comment by CZonin** [comment]
Running into the same issue with exactly the same setup.

```
2024-05-15 19:35:54.556 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.start()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 179, in start
    self._aiozc = AsyncZeroconf(ip_version=IPVersion.All)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/asyncio.py", line 166, in __init__
    self.zeroconf = zc or Zeroconf(
                          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 180, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

**Comment by CZonin** [comment]
Just an update:

Pulled the latest image from yesterday and seeing the same new error that @JohnGalt1717 posted.

```
2024-05-16 17:58:53.645 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.initialize(self.paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 130, in initialize
    await fetch_certificates(paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 209, in fetch_certificates
    last_fetch = await loop.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 206, in _check_paa_root_dir
    paa_root_cert_dir.mkdir()
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'
```

**Comment by marcelveldt** [comment]
6.0.1 has been released with a bugfix for the docker image.
For next time:

- the docker image is provided on a best-effort base - its not officially supported/maintained.
- create issue reports in the HA core repo if you are a HA user, not here

**Comment by CZonin** [comment]
> 6.0.1 has been released with a bugfix for the docker image. For next time:
> 
> * the docker image is provided on a best-effort base - its not officially supported/maintained.
> * create issue reports in the HA core repo if you are a HA user, not here

Confirmed this fixes the `FileNotFoundError: [Errno 2] No such file or directory error.`

@JohnGalt1717 for the `OSError: [Errno 105] No buffer space available` you can add `net.ipv4.igmp_max_memberships = 50` to `/etc/sysctl.conf`. That should fix the issue.
