### ISSUE TITLE
unable to start the matter container v6

### ISSUE THREAD

**Issue by tammeryousef1006** [home-assistant-libs/python-matter-server#703]
2024-05-15 12:50:22.176 (MainThread) INFO [matter_server.server.stack] CHIP Controller Stack initialized.
2024-05-15 12:50:22.178 (MainThread) INFO [matter_server.server.server] Starting the Matter Server...
2024-05-15 12:50:22.180 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.initialize(self.paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 130, in initialize
    await fetch_certificates(paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 209, in fetch_certificates
    last_fetch = await loop.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 206, in _check_paa_root_dir
    paa_root_cert_dir.mkdir()
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'

**Comment by marcelveldt** [comment]
First of all: Are you a developer or Home Assistant user ? Our issue report form indicates that for user support, please use the HA issue tracker so we can leave issues reported here for library consumers/developers. Also, running the Matter server in docker is officially not supported.

Nevertheless we'll take a look at this, to rule out something broke on fresh installs.

**Comment by tammeryousef1006** [comment]
im a Home Assistant user , i use the container method to test on several home assistant instances , i tried to report this at ha issue tracker but since im using container method so i thought i should report it here , sorry for the inconvenience
