### ISSUE TITLE
Upgrade from 5.10.0 to 6.0.0 failed

### ISSUE THREAD

**Issue by olavt** [home-assistant-libs/python-matter-server#704]
I tried upgrading from 5.10.0 to 6.0.0 by following these steps (using Docker images):
1) Stop the Python Matter Server 5.10.0
2) Start the Python Matter Server 6.0.0

This is the log with the error:

2024-05-15 13:46:11.688 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Logging...
2024-05-15 13:46:11.689 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Controller Stack...
[1715780771.761671][1:1] CHIP:CTL: Setting attestation nonce to random value
[1715780771.762448][1:1] CHIP:CTL: Setting CSR nonce to random value
[1715780771.764653][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1715780771.765303][1:1] CHIP:DL: writing settings to file (/tmp/chip_kvs-w6YX3f)
[1715780771.765527][1:1] CHIP:DL: renamed tmp file to file (/tmp/chip_kvs)
[1715780771.765940][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1715780771.766299][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_config.ini
[1715780771.766477][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_counters.ini
[1715780771.766892][1:1] CHIP:DL: writing settings to file (/data/chip_counters.ini-dIOv6g)
[1715780771.767428][1:1] CHIP:DL: renamed tmp file to file (/data/chip_counters.ini)
[1715780771.767533][1:1] CHIP:DL: NVS set: chip-counters/reboot-count = 2 (0x2)
[1715780771.768046][1:1] CHIP:DL: Got Ethernet interface: eth0
2024-05-15 13:46:11.769 (MainThread) WARNING [PersistentStorage] Initializing persistent storage from file: /data/chip.json
2024-05-15 13:46:11.769 (MainThread) WARNING [PersistentStorage] Loading configuration from /data/chip.json...
[1715780771.768345][1:1] CHIP:DL: Found the primary Ethernet interface:eth0
[1715780771.768501][1:1] CHIP:DL: Got WiFi interface: wlan0
[1715780771.768532][1:1] CHIP:DL: Failed to reset WiFi statistic counts
2024-05-15 13:46:11.976 (MainThread) WARNING [CertificateAuthorityManager] Loading certificate authorities from storage...
2024-05-15 13:46:11.976 (MainThread) WARNING [CertificateAuthority] New CertificateAuthority at index 1
2024-05-15 13:46:11.977 (MainThread) WARNING [CertificateAuthority] Loading fabric admins from storage...
2024-05-15 13:46:11.978 (MainThread) WARNING [FabricAdmin] New FabricAdmin: FabricId: 0x0000000000000001, VendorId = 0xFFF1
2024-05-15 13:46:11.979 (MainThread) INFO [matter_server.server.stack] CHIP Controller Stack initialized.
2024-05-15 13:46:11.986 (MainThread) INFO [matter_server.server.server] Starting the Matter Server...
2024-05-15 13:46:11.993 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.initialize(self.paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 130, in initialize
    await fetch_certificates(paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 209, in fetch_certificates
    last_fetch = await loop.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 206, in _check_paa_root_dir
    paa_root_cert_dir.mkdir()
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'

**Comment by mattkrau** [comment]
Same problem here:

```
2024-05-15 14:38:21.680 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Logging...
2024-05-15 14:38:21.680 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Controller Stack...
[1715783901.696427][1:1] CHIP:CTL: Setting attestation nonce to random value
[1715783901.696609][1:1] CHIP:CTL: Setting CSR nonce to random value
[1715783901.697176][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1715783901.697345][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1715783901.698445][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_config.ini
[1715783901.699314][1:1] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_counters.ini
[1715783901.701237][1:1] CHIP:DL: writing settings to file (/data/chip_counters.ini-PWGnih)
[1715783901.711141][1:1] CHIP:DL: renamed tmp file to file (/data/chip_counters.ini)
[1715783901.711393][1:1] CHIP:DL: NVS set: chip-counters/reboot-count = 70 (0x46)
[1715783901.711675][1:1] CHIP:DL: Got Ethernet interface: ens3
[1715783901.711885][1:1] CHIP:DL: Found the primary Ethernet interface:ens3
[1715783901.712296][1:1] CHIP:DL: Failed to get WiFi interface
[1715783901.712313][1:1] CHIP:DL: Failed to reset WiFi statistic counts
2024-05-15 14:38:21.712 (MainThread) WARNING [PersistentStorage] Initializing persistent storage from file: /data/chip.json
2024-05-15 14:38:21.713 (MainThread) WARNING [PersistentStorage] Loading configuration from /data/chip.json...
2024-05-15 14:38:21.796 (MainThread) WARNING [CertificateAuthorityManager] Loading certificate authorities from storage...
2024-05-15 14:38:21.796 (MainThread) WARNING [CertificateAuthority] New CertificateAuthority at index 1
2024-05-15 14:38:21.796 (MainThread) WARNING [CertificateAuthority] Loading fabric admins from storage...
2024-05-15 14:38:21.796 (MainThread) WARNING [FabricAdmin] New FabricAdmin: FabricId: 0x0000000000000001, VendorId = 0xFFF1
2024-05-15 14:38:21.817 (MainThread) INFO [matter_server.server.stack] CHIP Controller Stack initialized.
2024-05-15 14:38:21.818 (MainThread) INFO [matter_server.server.server] Starting the Matter Server...
2024-05-15 14:38:21.820 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.initialize(self.paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 130, in initialize
    await fetch_certificates(paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 209, in fetch_certificates
    last_fetch = await loop.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 206, in _check_paa_root_dir
    paa_root_cert_dir.mkdir()
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'
2024-05-15 14:40:20.012 (MainThread) WARNING [aiorun] Stopping the loop
2024-05-15 14:40:20.012 (MainThread) INFO [aiorun] Entering shutdown phase.
2024-05-15 14:40:20.012 (MainThread) INFO [aiorun] Executing provided shutdown_callback.
2024-05-15 14:40:20.012 (MainThread) INFO [matter_server.server.server] Stopping the Matter Server...
2024-05-15 14:40:20.013 (MainThread) INFO [aiorun] Waiting for executor shutdown.
2024-05-15 14:40:20.013 (MainThread) INFO [aiorun] Shutting down async generators
2024-05-15 14:40:20.013 (MainThread) INFO [aiorun] Closing the loop.
2024-05-15 14:40:20.013 (MainThread) INFO [aiorun] Leaving. Bye!
2024-05-15 14:40:20.013 (MainThread) INFO [aiorun] Reraising unhandled exception
2024-05-15 14:40:20.013 (MainThread) ERROR [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/matter-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/__main__.py", line 196, in main
    run(server.start(), shutdown_callback=handle_stop)
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 370, in run
    raise pending_exception_to_raise
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 270, in run
    loop.run_until_complete(shutdown_callback(loop))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/__main__.py", line 193, in handle_stop
    await server.stop()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 179, in stop
    raise RuntimeError("Server not started.")
RuntimeError: Server not started.
```

**Comment by afharo** [comment]
Same here: 
```
matter-server    | 2024-05-15 14:50:26.634 (MainThread) INFO [matter_server.server.server] Starting the Matter Server...
matter-server    | 2024-05-15 14:50:26.636 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
matter-server    | Traceback (most recent call last):
matter-server    |   File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
matter-server    |     await coro
matter-server    |   File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
matter-server    |     await self.device_controller.initialize(self.paa_root_cert_dir)
matter-server    |   File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 130, in initialize
matter-server    |     await fetch_certificates(paa_root_cert_dir)
matter-server    |   File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 209, in fetch_certificates
matter-server    |     last_fetch = await loop.run_in_executor(
matter-server    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
matter-server    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
matter-server    |     result = self.fn(*self.args, **self.kwargs)
matter-server    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
matter-server    |   File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 206, in _check_paa_root_dir
matter-server    |     paa_root_cert_dir.mkdir()
matter-server    |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
matter-server    |     os.mkdir(self, mode)
matter-server    | FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'
```

**Comment by dziban303** [comment]
Same here!

**Comment by holocronweaver** [comment]
Please thumbs up the issue if you experience this to avoid cluttering the issue with repeat logs.

**Comment by simmac** [comment]
This also happens with a fresh installation btw, so it's not an upgrading issue per se

**Comment by dorsanty** [comment]
To workaround I did a `mkdir -p /usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs` within the running container and restarted it. The server started fine and downloaded the files it needed.

To me it looks like the script `paa_certificates.py` should use `os.mkdirs` in order to guarantee the parent directories are created alongside the one it needs to create

**Comment by D3v01dZA** [comment]
Any new container will have this issue. If your workflow requires that you delete and recreate the container you can probably also temporarily mount the directory as a volume.

```
volumes:
  - './dirtyhack:/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'
```

**Comment by tammeryousef1006** [comment]
now its working this way thanks for @D3v01dZA 

version: "3.8"
services:
  # python-matter-server
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
      - './dirtyhack/:/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs/'

**Comment by tammeryousef1006** [comment]
version: "3.8"
services:
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
      - './dirtyhack/:/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs/'

**Comment by holocronweaver** [comment]
@agners Maybe re-open the issue until the fix is released in a new docker image?

**Comment by imcdona** [comment]
It's concerning that a bug of this magnitude somehow made it into the "stable" build.

**Comment by D3v01dZA** [comment]
Bugs happen. Docker is not something they officially provide support for, same as Home Assistant and the add on was unaffected.

**Comment by D3v01dZA** [comment]
@afharo its not specific to Docker. 

The add-on overrides the location of paa certs to /data/ so it doesn't fail https://discord.com/channels/330944238910963714/986700592145645579/1241297942443458560. I believe that the team only officially supports the add-on so anybody not running that is getting best effort and some things may fall through the cracks like this (this is much too complicated of a topic/perspective/strategy/whatever to tackle in comments).

**Comment by MadSpindel** [comment]
Version 6.0.1 is now available! I've tried it and now it works for me again.

**Comment by imcdona** [comment]
@D3v01dZA 

> Bugs happen. Docker is not something they officially provide support for, same as Home Assistant and the add-on was unaffected.

Whether it's officially supported or not is beside the point. When an image is tagged as "stable", the expectation is that the image has passed basic sanity checking.

A git commit pipeline that launches the image in a docker container and issues a request or two via curl would ensure that bugs like this are caught early.

I have experience building pipelines in GitLab but haven't yet built one on GitHub. I'll see if I can't come up with something and issue a merge request when I get some free time.

**Comment by D3v01dZA** [comment]
@imcdona and this is why this is too nuanced for a comment thread, you're applying all sorts of your own ideas to a word. "stable" === "based-on-stable-code" when it comes to Docker for the projects perspective.

The maintainers perspective can be found here - if I was him I'd stop building the Docker image and make everyone build their own given how entitled everyone feels to his work. https://github.com/home-assistant-libs/python-matter-server/pull/706#issuecomment-2120619780

**Comment by imcdona** [comment]
If the maintainer doesn't want to provide the impression that the image is stable, he shouldn't be using the _stable_ tag. The developers contention in the linked comment is in reference to the _latest_ tag, which is applied automatically by the docker daemon to whatever the latest version of the image is. And yes, it's bad practice to use the _latest_ tag if you are looking for stability, hence a separate tag for _stable_.

For some reason, this image was tagged as _stable_ when it obviously wasn't. I expect to see issues like this when using _latest_, but not stable.

**Comment by D3v01dZA** [comment]
> you're applying all sorts of your own ideas to a word

Your answer just did this again, this is _not_ what the project defines as the 'stable' image. The maintainer already told you if you want a stable supported server go install HassOS and use the add-on.

**Comment by imcdona** [comment]
> if you want a stable supported server go install HassOS and use the add-on.

It could be that they are tagging the code as _stable_, as in stable for HassOS and the docker image is inadvertently tagged as a result. If that's the case, then an exception needs to be added so the docker image doesn't inherit the _stable_ tag. 

If there's no difference between the _latest_ and _stable_ tags, do us all a favor and remove the _stable_ tag from the docker image.

**Comment by D3v01dZA** [comment]
Now I think we have a common understanding. 

I actually agree with you that "stable" is misleading when it comes to this. What to do about it is also questionable, the project does not consider the container as "supported" so you're unlikely to get a true "stable" workflow for Docker unless someone wants to contribute their time to making and maintaining that and its workflow (I think your idea is a good starting point). 

Besides any of that, revoking the "stable" tag (because it doesn't seem to be what most folks consider "stable") is likely to make even more people unhappy as they would no longer receive updates etc.

**Comment by agners** [comment]
Currently testing is mostly limited to the add-on: The add-on has the beta flag, which installs the latest beta releases from pip. We (and users) usually use this to test beta release in real-world setups. Then once release comes around, I usually just sanity check the full integration with the add-on again. But pure container testing falls a bit short, that is where the bug now was hiding :cry: 

However: Keep in mind the add-on is built from the container (see it's [build configuration](https://github.com/home-assistant/addons/blob/master/matter_server/build.yaml))! So almost all bugs will be captured by this setup, *unless* the bug hides between that small container vs. add-on specific configuration/parameter difference... :cry: 

> I actually agree with you that "stable" is misleading when it comes to this. What to do about it is also questionable, the project does not consider the container as "supported" so you're unlikely to get a true "stable" workflow for Docker unless someone wants to contribute their time to making and maintaining that and its workflow (I think your idea is a good starting point).

Well, with my above comment in mind, I don't think it is that bad. I'd say test coverage is about 98% already. We just got a bit unlucky this time to introduce a bug in this 2% of code which is only run in the container setup. And in this case, in the *default* container configuration. But yeah, I agree wit this statement:

> A git commit pipeline that launches the image in a docker container and issues a request or two via curl would ensure that bugs like this are caught early.

That is an excellent idea! And it would have caught this bug.

If someone is willing to contribute such a GitHub Action pipeline, I am happy to review or give pointers. In any case, I will bring this up internally, I definitely think we should add that. It's is also a good thing for the add-on, as it relies on the container.
