### ISSUE TITLE
Checksum mismatch even though checksum is correct

### ISSUE THREAD

**Issue by dd310** [home-assistant-libs/python-matter-server#817]
Firmware update for the Eve Energy plug fails with the following error
```
 INFO [matter_server.server.device_controller] <Node:8> New software update found: 3.2.1 on UpdateSource.MAIN_NET_DCL (current 3.2.0).
2024-07-19 14:16:42.398 (MainThread) INFO [matter_server.server.device_controller] <Node:8> Update to software version 6650
2024-07-19 14:16:42.548 (MainThread) INFO [matter_server.server.device_controller] <Node:8> New software update found: 3.2.1 on UpdateSource.MAIN_NET_DCL (current 3.2.0).
2024-07-19 14:16:42.549 (MainThread) INFO [matter_server.server.device_controller] <Node:8> Downloading update from 'https://eve-updates.evehome.com/matter/eve_energy_eu-3.2.1-matter-benc-enc-4E71C921-3218-4E56-9928-527DA7A3BE88.bin'
[New Thread 0x7fffe9efc700 (LWP 256)]
2024-07-19 14:16:42.720 (MainThread) ERROR [matter_server.server.ota.provider] Checksum mismatch for file 'eve_energy_eu-3.2.1-matter-benc-enc-4E71C921-3218-4E56-9928-527DA7A3BE88.bin', expected:  MO+9nc1o5vG74qC85pvd9MVe6QGbFQNbG2mbQvzRIVA=, got: MO+9nc1o5vG74qC85pvd9MVe6QGbFQNbG2mbQvzRIVA=
2024-07-19 14:16:42.721 (MainThread) ERROR [matter_server.server.client_handler] [140737121555088] Error while handling: update_node (node 8): Checksum mismatch!
```

**Comment by agners** [comment]
Hm, I see, the reason is a spurious whitespace in the DCL entry. I'll report and trim before comparing the checksum.

**Comment by dd310** [comment]
I tested the new beta that was just released, but now when I try to update the Eve Energy this error shows up:

```
2024-07-22 23:43:04.007 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 214, in _run_handler raise err File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 197, in _run_handler result = await result ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 917, in check_node_update update_source, update = await self._check_node_update(node_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1027, in _check_node_update if "otaUrl" not in update or update["otaUrl"].strip().length == 0: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'str' object has no attribute 'length'
```

**Comment by agners** [comment]
Gah right, fixed with: https://github.com/home-assistant-libs/python-matter-server/pull/834
