### ISSUE TITLE
matter server doesn't properly handle SIGTERM when server failed to start

### ISSUE THREAD

**Issue by doubledgedboard** [home-assistant-libs/python-matter-server#835]
I had an upgrade issue which caused the server to be in a 'non-running' state, but the process hadn't actually exited:

(ignore the specific error here, this is just to show that the service was still running)

```
● matterserver.service - matterserver
     Loaded: loaded (/etc/systemd/system/matterserver.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-07-23 18:56:01 CDT; 14s ago
   Main PID: 817 (python)
      Tasks: 4 (limit: 1093)
     Memory: 80.5M
        CPU: 1.668s
     CGroup: /system.slice/matterserver.service
             └─817 /srv/homeassistant/bin/python -m matter_server.server

Jul 23 18:56:03 homeassistant python[817]: 2024-07-23 18:56:03.065 (MainThread) INFO [matter_server.server.stack] CHIP Controller Stack initialized.
Jul 23 18:56:03 homeassistant python[817]: 2024-07-23 18:56:03.065 (MainThread) INFO [matter_server.server.server] Starting the Matter Server...
Jul 23 18:56:03 homeassistant python[817]: 2024-07-23 18:56:03.069 (MainThread) ERROR [asyncio] Task exception was never retrieved
Jul 23 18:56:03 homeassistant python[817]: future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /srv/homeassistant/lib/python3.12/si>
Jul 23 18:56:03 homeassistant python[817]: Traceback (most recent call last):
Jul 23 18:56:03 homeassistant python[817]:   File "/srv/homeassistant/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
Jul 23 18:56:03 homeassistant python[817]:     await coro
Jul 23 18:56:03 homeassistant python[817]:   File "/srv/homeassistant/lib/python3.12/site-packages/matter_server/server/server.py", line 160, in start
Jul 23 18:56:03 homeassistant python[817]:     raise VersionMismatch(
Jul 23 18:56:03 homeassistant python[817]: matter_server.common.errors.VersionMismatch: CHIP Core version does not match CHIP Clusters version.
```

however, when attempting to stop it with a `systemctl stop matterserver`, the service becomes hung, failing to properly handle `SIGTERM`

```
● matterserver.service - matterserver
     Loaded: loaded (/etc/systemd/system/matterserver.service; enabled; preset: enabled)
     Active: deactivating (stop-sigterm) since Tue 2024-07-23 18:56:25 CDT; 1min 4s ago
   Main PID: 817 (python)
      Tasks: 2 (limit: 1093)
     Memory: 82.5M
        CPU: 1.781s
     CGroup: /system.slice/matterserver.service
             └─817 /srv/homeassistant/bin/python -m matter_server.server

Jul 23 18:56:25 homeassistant python[817]:   File "/srv/homeassistant/lib/python3.12/site-packages/aiorun.py", line 270, in run
Jul 23 18:56:25 homeassistant python[817]:     loop.run_until_complete(shutdown_callback(loop))
Jul 23 18:56:25 homeassistant python[817]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
Jul 23 18:56:25 homeassistant python[817]:     return future.result()
Jul 23 18:56:25 homeassistant python[817]:            ^^^^^^^^^^^^^^^
Jul 23 18:56:25 homeassistant python[817]:   File "/srv/homeassistant/lib/python3.12/site-packages/matter_server/server/__main__.py", line 230, in handle_stop
Jul 23 18:56:25 homeassistant python[817]:     await server.stop()
Jul 23 18:56:25 homeassistant python[817]:   File "/srv/homeassistant/lib/python3.12/site-packages/matter_server/server/server.py", line 216, in stop
Jul 23 18:56:25 homeassistant python[817]:     raise RuntimeError("Server not started.")
Jul 23 18:56:25 homeassistant python[817]: RuntimeError: Server not started.
```

`home-assistant-chip-clusters-2024.7.0`

`python-matter-server-6.3.0`

**Comment by marcelveldt** [comment]
Running a production setup with just installing the python packages is NOT supported.
Please read the documentation.

**Comment by doubledgedboard** [comment]
marcel, why the defensive attitude?
